<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Articles</span></div>
        <div class="content">

             <div id="UITab">
                        <ul class="tabs">
                            <li><a href="/admin/articles">Articles</a></li>   
                            <li><a href="/admin/articles/view/id/<?php echo $this->data['aid'] ?>"><?php echo $this->data['title'] ?></a></li>
                            <li class="active"><a href="#">Edit</a></li>          
                        </ul>
                        <div id="diagTrBrandStore">
                            <form enctype="multipart/form-data" id="formTrBrandStore" action="/admin/articles/edit-tr/id/<?php echo $this->data['tr_aid'] ?>" method="<?php echo $this->form->getMethod(); ?>">
                                <?php echo $this->form->aid ?>
                                <div class="section"><label>Locale</label><div><?php echo $this->form->locale ?></div></div>
                                <div class="section"><label>Title</label><div><?php echo $this->form->title ?></div></div>
                                <div class="section"><label>Content</label><div><?php echo $this->form->content ?></div></div>
                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Submit</a></div>
                                </div>
                            </form>
                        </div>
             </div>
        </div>
</div>