<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Articles</span></div>
        <div class="content">
                <div id="UITab">
                        <ul class="tabs">
                            <li><a href="/admin/articles">Articles</a></li>   
                            <li class="active"><a href="#"><?php echo $this->action ?></a></li>          
                        </ul>
                        <form enctype="multipart/form-data" name="formBrandStore" id="formBrandStore" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                                <div class="section">
                                        <label>Article Type<small>required.</small></label>   
                                        <div><?php echo $this->form->article_type; ?></div>
                                </div>
                                <div class="section">
                                        <label>Title<small>required.</small></label>   
                                        <div><?php echo $this->form->title; ?></div>
                                </div>

                                <div class="section">
                                        <label>Latitude <small>required.</small></label>   
                                        <div><?php echo $this->form->lat; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Longitude <small>required.</small></label>   
                                        <div><?php echo $this->form->lgt; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Begin<small>required.</small></label>   
                                        <div><?php echo $this->form->stime; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>End <small>required.</small></label>   
                                        <div><?php echo $this->form->etime; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Status <small>required.</small></label>   
                                        <div><?php echo $this->form->status; ?></div>
                                </div>
                            
                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Submit</a></div>
                                </div>

                        </form>
                </div>
        </div>
</div>