<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Articles</span></div>
        <div class="content">
                <div id="UITab">
                        <ul class="tabs">
                            <li><a href="/admin/articles">Articles</a></li>   
                            <li class="active"><a href="#"><?php echo $this->action ?></a></li>          
                        </ul>
                    
                        <form>
                                <div class="section">
                                        <label>Article Type<small>required.</small></label>   
                                        <div><?php echo $this->article['article_type']; ?></div>
                                </div>
                                <div class="section">
                                        <label>Title<small>required.</small></label>   
                                        <div><?php echo $this->article['title']; ?></div>
                                </div>

                                <div class="section">
                                        <label>Latitude <small>required.</small></label>   
                                        <div><?php echo $this->article['lat']; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Longitude <small>required.</small></label>   
                                        <div><?php echo $this->article['lgt']; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Begin<small>required.</small></label>   
                                        <div><?php echo $this->article['stime']; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>End <small>required.</small></label>   
                                        <div><?php echo $this->article['etime']; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Status <small>required.</small></label>   
                                        <div><?php echo $this->article['status']; ?></div>
                                </div>
                            
                                <?php if ($this->translate_article) { ?>
                                    <?php foreach($this->translate_article as $tr_article) { ?>
                                        <div class="section">
                                                <label>Locale <small>required.</small></label>   
                                                <div><?php echo $tr_article['locale']; ?></div>
                                        </div>
                                        <div class="section">
                                                <label>Title <small>required.</small></label>   
                                                <div><?php echo $tr_article['title']; ?></div>
                                        </div>
                                        <div class="section">
                                                <label>Content <small>required.</small></label>   
                                                <div><?php echo $tr_article['content']; ?></div>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                        </form>
                    
                </div>
        </div>
</div>