<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Hotel Users</span></div>
        <div class="content">
                <div id="UITab">
                        <ul class="tabs">
                            <li><a href="/admin/hotel-users">Hotel Users</a></li>   
                            <li class="active"><a href="#"><?php echo $this->action ?></a></li>          
                        </ul>
                        <form enctype="multipart/form-data" name="formHotelUsers" id="formHotelUsers" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                                <div class="section">
                                        <label>Hotel</label>
                                        <div><?php echo $this->form->hid; ?></div>
                                </div>

                                <div class="section">
                                        <label>User</label>   
                                        <div><?php echo $this->form->uid; ?></div>
                                </div>

                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Valider</a></div>
                                </div>

                        </form>
                </div>
        </div>
</div>