<div class="widget" >
    <div class="header"><span ><span class="ico gray window"></span>Hotel Users</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="#tab2">Hotel Users</a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a brand">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3>List</h3>
                            <table class="display data_table2" id="hotels" width="100%">
                                <thead>
                                    <tr>
                                        <th>Hotel User ID</th>
                                        <th>Hotel ID</th>
                                        <th>Hotel Name</th>
                                        <th>User ID</th>
                                        <th>User Email</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->focusRowArray as $row): ?>
                                    <tr>
                                        <td><?php echo $row['huid'] ?></td>
                                        <td><a href="/admin/hotels/view/id/<?php echo $row['hid'] ?>"><?php echo $row['name'] ?></a></td>
                                        <td><?php echo $row['lat']?></td>
                                        <td><?php echo $row['lgt'] ?></td>
                                        <td><?php echo $row['world'] ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/brand/edit/id/<?php echo $row['hid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/brand/delete/id/<?php echo $row['hid'] ?>" class="delete" name="<?php echo $this->escape($row['name']); ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
