<div class="widget">
    <div class="header"><span ><span class="ico gray window"></span>Hotels</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/hotels">hotels</a></li>   
                <li class="active"><a href="#"><?php echo $this->focusRowArray[0]['name'] ?></a></li>          
            </ul>
            
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <form>
                            <div class="section">
                                <label>Name</label> 
                                <div><?php echo $this->focusRowArray[0]['name']; ?><a href="/admin/hotels/add-tr/id/<?php echo $this->focusRowArray[0]['hid'] ?>" class="uibutton icon add" style="float:right; margin-bottom: 0px; margin-top: -10px;" >Add new translation</a></div>
                            </div>
                            
                                <?php if ($this->focusRowArray[0]['tr_hid']) { ?>
                                <div style="margin: 20px 0px 20px 50px;" >
                                <?php foreach ($this->focusRowArray as $row) { ?>
                                    <div class="section">
                                        <label><small><?php echo $row['locale']; ?></small></label> 
                                        <div><?php echo $row['title']; ?><span class="tip" style="float:right;"><a href="/admin/hotels/edit-tr/id/<?php echo $row['tr_hid'] ?>"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span></div>
                                        <?php if ($row['address']) { ?> <div style="margin-top: 10px;"><?php echo $row['address']; ?></div> <?php } ?>
                                        <?php if ($row['content']) { ?> <div style="margin-top: 10px;"><?php echo $row['content']; ?></div> <?php } ?>
                                    </div>
                                <?php } ?>
                                </div>
                                <?php } ?>
                            
                            <div class="section">
                                    <label>World Name</label>   
                                    <div><?php echo $this->focusRowArray[0]['world_name'] ?></div>
                            </div>

                            <div class="section">
                                    <label>Latitude</label>   
                                    <div><?php echo $this->focusRowArray[0]['lat']; ?></div>
                            </div>

                            <div class="section last">
                                    <label>Longitude</label>   
                                    <div><?php echo $this->focusRowArray[0]['lgt']; ?></div>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>