<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Hotels</span></div>
        <div class="content">
                <div id="UITab">
                        <ul class="tabs">
                            <li><a href="/admin/hotels">Hotels</a></li>   
                            <li class="active"><a href="#"><?php echo $this->action ?></a></li>          
                        </ul>
                        <form enctype="multipart/form-data" name="formTranslateHotels" id="formTranslateHotels" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                                <div class="section">
                                        <label>Name <small>required.</small></label>   
                                        <div><?php echo $this->form->name; ?></div>
                                </div>

                                <div class="section">
                                        <label>Latitude <small>optional.</small></label>   
                                        <div><?php echo $this->form->lat; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Longitude <small>optional.</small></label>   
                                        <div><?php echo $this->form->lgt; ?></div>
                                </div>

                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Valider</a></div>
                                </div>

                        </form>
                </div>
        </div>
</div>