<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <?php if ($_COOKIE['locale'] == 'en_US') { ?>
                    <?php echo $this->page['content_en']; ?>
                <?php } else { ?>
                    <?php echo $this->page['content']; ?>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>