                <div class="image_layer image_layer_small">
                    <div class="mask_layer">
                        <div class="text_layer_big">
                            <div id="text_container" class="plan_de_transport-network">
                                <div class="section left">
                                    <div class="title">PLAN DE TRANSPORT</div>
                                    <div class="form" id="transport-form">
                                        <form id="form-transport">
                                            <div class="depart">
                                                <label>
                                                    <span class="label">Depart</span>
                                                    <span class="field">
                                                        <select name="" id="">
                                                        <option value="" label="">ANVERS PSA</option>
                                                    </select>
                                                    </span>
                                                </label>
                                            </div>
                                            <div class="arrivee">
                                                <label>
                                                    <span class="label">Arrivee</span>
                                                    <span class="field">
                                                        <select name="" id="">
                                                        <option value="" label="">LYON</option>
                                                    </select>
                                                    </span>
                                                </label>
                                            </div>
                                            <div class="submit">
                                                <span class="label">&nbsp;</span>
                                                <span><img src="/medias/images/ok.png"></span>
                                            </div>
                                        </form>
                                        <div class="closing">
                                            <label>Closing Booking > </label>
                                            <ul class="dot">
                                                <li>Depart Anvers PSA : Jour A-1 12h00</li>
                                                <li>Depart Lyon: Jour A-1 12h00</li>
                                            </ul>
                                        </div>
                                        <div class="closing">
                                            <label>Closing Documentation > </label>
                                            <ul class="dot">
                                                <li>Depart Anvers PSA : Jour A-1 12h00</li>
                                                <li>Depart Lyon: Jour A-1 12h00</li>
                                            </ul>
                                        </div>
                                        <div class="block">
                                            <span class="bold">MAD* tous quals Anvers > </span>
                                            <span class="normal">Jour C par route (sauf Vendredi: MDA le Mardi)</span>
                                        </div>
                                        <div class="block">
                                            <span class="bold">Closing tous quais Anvers > </span>
                                            <span class="normal">Jour A-1 par route</span>
                                        </div>
                                        
                                        <p>Ces relations representent 
                                            <span class="bold">un gain de 
                                                <span class="big_number">6</span><span class="big_number">6</span><span class="big_number">6</span> TJ </span> 
                                            par rapport a un scenario routier
                                        </p>
                                        
                                    </div>
                                </div>
                                <div class="section right">
                                    <div class="block1">
                                        <span class="label">Lyon VENISSIEUX > Anvers PSA T.913</span>
                                        <table>
                                            <tr>
                                                <th>HLR<span>*</span></th>
                                                <th>MAD<span>*</span></th>
                                                <th>Delai</th>
                                            </tr>
                                            <tr>
                                                <td>Lun 19h00</td>
                                                <td>Ma 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Lun 19h00</td>
                                                <td>Ma 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Me 19h00</td>
                                                <td>Je 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Je 19h00</td>
                                                <td>Ye 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Ye 19h00</td>
                                                <td>Lu 10h00</td>
                                                <td>AD</td>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="block1">
                                        <div class="label">Lyon VENISSIEUX > Anvers PSA T.913</div>
                                        <table>
                                            <tr>
                                                <th>HLR<span>*</span> (check)</th>
                                                <th>MAD<span>*</span></th>
                                                <th>Delai</th>
                                            </tr>
                                            <tr>
                                                <td>Lun 19h00</td>
                                                <td>Ma 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Lun 19h00</td>
                                                <td>Ma 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Me 19h00</td>
                                                <td>Je 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Je 19h00</td>
                                                <td>Ye 10h00</td>
                                                <td>AB</td>
                                            </tr>
                                            <tr>
                                                <td>Ye 19h00</td>
                                                <td>Lu 10h00</td>
                                                <td>AD</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                 <div class="section bottom">
                                     <label><span class="bold">*MAD</span> > Mise A Disposition</label>
                                     <label><span class="bold">*HLR</span> > Heure Limite de Remise</label>
                                     <label><img src="/medias/images/pdf.png"> Teleoharger</label>
                                     <label><img src="/medias/images/pdf.png"> Teleoharger</label>
                                     <label><img src="/medias/images/imprimante.png"> Imprimer</label>
                                </div>
                            </div>
                            </div>
                        </div>
                </div>   
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>