<div class="image_layer image_layer_big" id="<?php echo $this->controller . '_' . $this->action ?>">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Ferro-Maritime</div>
                <div class="subtitle">LE TRANSPORT SOUS DOUANE GRACE A LA CONFIANCE DES DOUANES FRANCAISES</div>
                <div class="text">
                    <p>La procédure Ferro-Maritime permet à Naviland Cargo:</p>
                </div>
            </div>
        </div>
    </div>
 </div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>