<div class="image_layer image_layer_big" id="<?php echo $this->controller . '_' . $this->action ?>">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Navi-Trucking</div>
                <div class="text">
                    <p>Sous la marque NAVI-TRUCKING, Naviland Cargo dispose d’une offre ‘’tout-route‘’ complémentaire au transport combiné. NAVI-TRUCKING réalise à la fois des acheminements longue distance  et des prestations de courte distance sur les derniers kilomètres. Cette activité, support de notre offre combiné, est une pièce maîtresse de la chaîne logistique. </p>
                    <p>Les moyens de Navi-trucking permettent ainsi à nos clients de toujours bénéficier de solutions d’affrètements routiers en cas d’aléas dans le respect des délais.</p>
                    <p>Avec quatre agences en France (Fos sur mer , Bordeaux , Le Havre et Strasbourg), NAVI-TRUCKING   propose  principalement  ses services sur  le  concept du One Way en France comme  en Europe  et offre ainsi des solutions supplémentaires et  une  flexibilité reconnue  par notre clientèle. </p>
                    <div class="ul_title">Contacts Navi-Trucking</div>
                    <ul class="dot">
                        <li>Le Havre : +33 (0)2 35 25 00 79     ou <br>navitrucking_lehavre@naviland-cargo.com </li>
                        <li>Fos : + 33(0)4 42 48 92 12      ou <br>navitrucking_fos@naviland-cargo.com </li>
                        <li>Bordeaux : + 33 (0)5 56 49 81 57    ou <br>navitrucking_bordeaux@naviland-cargo.com </li>
                        <li>Strasbourg : + 33 (0)3 88 56 64 13      ou <br>navitrucking_strasbourg@naviland-cargo.com</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
 </div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>