<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Offre terminalistique</div>
                <div class="subtitle">UN MAILLON FORT DE NOTRE CHAINE DE VALEUR</div>
                <div class="text">
                    <p>A proximité immédiate des centres de distribution/consommation majeurs, nous exploitons un réseau de 10 terminaux de transport combiné dont huit opérés en propre. Nos équipes procèdent à l'accueil des trains, à la réception et à la manutention des conteneurs. Elles réalisent des opérations de gardiennage, de maintenance et de réparations. Nous mettons à disposition de nos clients sur nos terminaux d'importantes capacités de stockage (10000 EVP) qui favorisent la massification des envois et concourent à l'équilibre des flux.</p>
                    <p>En complément de ces activités de terminaliste, nous avons  développé une activité de stockage et de maintenance de conteneurs vides associée à des prestations de gestion informatisée de parc de conteneurs.</p>
                    <p>Sur nos terminaux, nous proposons les prestations suivantes :</p>
                    <ul class="dot">
                        <li>Stockage des conteneurs</li>
                        <li>Réparation et Maintenance des conteneurs</li>
                        <li>Gestion de parc informatisée</li>
                        <li>Le gardiennage des conteneurs chargés</li>
                        <li>Des aires de stockage sous douane : MADT</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
 </div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>