<div class="image_layer image_layer_big" id="<?php echo $this->controller . '_' . $this->action ?>">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Track & Trace</div>
                <div class="subtitle">LE SUIVI INFORMATISE DES COMMANDES</div>
                <div class="text">
                    <p>Notre système d’information s’adapte en continu aux dernières innovations logicielles. 
                        Il  intègre ainsi la gestion de parc matériel par EDI (Echange de données informatisées), 
                        la passation et le suivi des commandes en temps réel via internet. Ce service de  Track & 
                        Trace offre à nos clients la possibilité d’être informés durant tout le trajet du conteneur. 
                        Il offre en flux continu le suivi depuis la prise de commande, l’organisation des transports Fer et Route, 
                        la gestion des prestations terminalistiques, et la facturation de l’ensemble de nos prestations. </p>
                    <p>Un flux d’informations continu durant tout le trajet du conteneur (de la prise de la réservation jusqu’à la livraison finale)</p>
                    <img src="/medias/images/illustrations/service_chart.png" >
                </div>
            </div>
        </div>
    </div>
 </div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>