<div class="image_layer image_layer_big" id="<?php echo $this->controller . '_' . $this->action ?>">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Transport Combiné</div>
                <div class="subtitle">LEADER DU COMBINE MARITIME</div>
                <div class="text">
                    <div class="subtitle2">UNE CHAINE LOGISTIQUE INTEGREE</div>
                    <p>Leaders européen du combiné maritime, nous opérons une activité de transport import/export sur le marché de l’overseas où transitent 95% des marchandises échangées au niveau mondial. Nous organisons et réalisons pour le compte de nos clients ;  des prestations de transport combiné de conteneurs maritimes, caisses mobiles, citernes et vrac associant les modes ferroviaires et routiers en une seule et même chaine logistique.</p>
                    <p>Nos équipes organisent au quotidien notre propre traction ferroviaire au moyen de locomotives, wagons et de nos propres conducteurs </p>
                    
                    <div class="subtitle2">FIABILITE ET PONCTUALITE : UNE OFFRE DE TRANSPORT « PORTE-A-PORTE »</div>
                    <p>Depuis le site du chargeur jusqu’au port, puis du port jusqu’aux bassins industriels et économiques, nous proposons à nos clients une prestation de transport de marchandises porte-à-porte,. Fiabilité et ponctualité sont les valeurs développées et partagées par l’ensemble de l’entreprise dont 96% de la production ferroviaire ne fait l’objet d’aucun retard. La gestion maitrisée des trafics nous permet par ailleurs de proposer à nos clients des plages horaires de distribution très étendues. En 2011, nous avons fait circuler 7000 trains et acheminé 400000 EVP (Equivalent vingt pieds).</p>
                    
                    <div class="subtitle2">CAPACITES DEDIEES ET « COMPANY TRAINS » : DES CONCEPTS NOVATEURS</div>
                    <p>Au delà de l’offre de transport standard, nous développons des concepts innovants. Nous pouvons ainsi sur demande de nos clients allouer des capacités (ou prises de slots) sous forme d’espace dans un wagon ou plusieurs wagons. Nous proposons également des services de trains dédiés à un seul client ( « company trains »).</p>

                    <div class="subtitle2">UNE EXPERTISE RECONNUE DANS LE TRANSPORT DE  PRODUITS DANGEREUX</div>
                    <p>Nous proposons à notre clientèle des prestations de transport de marchandises dangereuses dans le strict respect des réglementations en vigueur (ADR/RID). Nous sommes ainsi reconnus comme sous traitant agréé des transporteurs autorisés auprès du haut fonctionnaire de défense et de sécurité (HFDS).</p>
                    <p>Des conseillers à la sécurité pour le transport des marchandises dangereuses (CSTMD) accompagnent nos clients dans le suivi et le contrôle des obligations réglementaires sur l’ensemble des classes autorisées dans les conditions normales de transport et de sécurité.</p>
                    
                    <div class="subtitle2">UNE VISION RESOLUMENT EUROPEENNE AU SERVICE DES CLIENTS</div>
                    <p>La zone d’influence (ou Hinterland) des grands ports européens étant emmenée à s’étendre, nos perspectives de développement accompagnent cette tendance. Que ce soit en propre ou à travers des des partenariats avec des opérateurs étrangers nous proposons à l’ensemble de notre clientèle l’accès aux plateformes de distribution majeures en Europe. Ces accords et implantations nous permettent d’étendre la couverture de nos services aux pays scandinaves, l’Europe de l’Est, l’Asie centrale et l’Asie orientale.</p>
                </div>
            </div>
        </div>
    </div>
 </div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>