<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>Brand Stores</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="#tab2">Brand Stores</a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a brand store">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="languages" width="100%">
                                <thead>
                                    <tr>
                                        <th>Brand Store ID</th>
                                        <th>Brand</th>
                                        <th>Latitude</th>
                                        <th>Longitude</th>
                                        <th>World</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->stores as $store): ?>
                                    <tr>
                                        <td><?php echo $store['bsid'] ?></td>
                                        <td><?php echo $store['brand'] ?></td>
                                        <td><?php echo $store['lat'] ?></td>
                                        <td><?php echo $store['lgt'] ?></td>
                                        <td><?php echo $store['world'] ?></td>
                                        <td><?php echo $store['status'] ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/brand-stores/add-locale/bsid/<?php echo $store['bsid'] ?>" class="add_locale" id="add_locale_tr_bsid_<?php echo $store['bsid'] ?>">Add Locale</a></span>
                                            <span class="tip"><a href="/admin/brand-stores/edit/id/<?php echo $store['bsid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/brand-stores/delete/id/<?php echo $store['bsid'] ?>" class="delete" name="<?php echo $this->escape($store['bsid']); ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>

<div class="dialog" style="display:none;">
                <label>Locale</label>   
                <input type="text" name="locale" id="locale" value="" />
</div>

<script type="text/javascript">
$(function(){
    $('.add_locale').click(function(event) {
        /*
        event.preventDefault();
        var bsid = $(this).attr('id').substring(19);
        $('.dialog').dialog({
            height: 200,
            width: 350,
            title: 'ADD A NEW LOCALE'
            buttons: {
                "Submit": function() {
                    
                }, 
                "Cancel": function() {
                    $(this).dialog("close");
                }
            },
            close: function() {
                $('#locale').val('');
            }
        });
        */
    });
});
</script>