<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>Brand Stores</span></div>
        <div class="content">

             <div id="UITab">
                        <ul class="tabs">
                            <li><a href="<?php $this->url(array('controller'=>'brand-stores', 'action'=>'index', 'module'=>'admin'), 'default', true) ?>">Brand Stores</a></li>   
                            <li><a href="/admin/brand-stores/view/id/<?php echo $this->data['bsid'] ?>"><?php echo $this->data['brand_store_name'] ?></a></li>
                            <li class="active"><a href="#">Add</a></li>          
                        </ul>
                        <div id="diagTrBrandStore">
                            <form enctype="multipart/form-data" id="formTrBrandStore" action="/admin/brand-stores/add-tr" method="<?php echo $this->form->getMethod(); ?>">
                                <input type="hidden" name="bsid" value="<?php echo $this->data['bsid'] ?>" id="bsid">
                                <div class="section"><label>Locale</label><div><?php echo $this->form->locale ?></div></div>
                                <div class="section"><label>Title</label><div><?php echo $this->form->title ?></div></div>
                                <div class="section"><label>Content</label><div><?php echo $this->form->content ?></div></div>
                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Submit</a></div>
                                </div>
                            </form>
                        </div>
             </div>
        </div>
</div>