<div class="widget">
        <div class="header">
                <span><span class="ico gray window"></span>Languages</span>
        </div>	
        
        <div class="content">
                <form enctype="multipart/form-data" name="formPosts" id="formPosts" action="" method="post">
                        <div class="section">
                                <label>Locale <small>required.</small></label>   
                                <div><?php echo $this->postsForm->tag_id; ?></div>
                        </div>

         <div class="section last">
                                            <div>
                                                    <a class="uibutton submit_form" >Valider</a>
                                            </div>
                                    </div>

            </form>

        </div>
</div>
                   

