<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>Languages</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="#tab2"><?php echo $this->translate('languages') ?></a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li id="btnAddLang"><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a language">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="languages" width="100%">
                                <thead>
                                    <tr>
                                        <th>Locale</th>
                                        <th>Title</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->languages as $language): ?>
                                    <tr>
                                        <td><?php echo $language['locale']?></td>
                                        <td><?php echo $language['title'] ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/languages/edit/id/<?php echo $language['lid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/languages/delete/id/<?php echo $language['lid'] ?>" class="delete" name="<?php echo $this->escape($language['locale']) . ', ' . $this->escape($language['title']); ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>

<div id="diagAddLang" style="display:none;">
    
</div>
<script type="text/javascript"> 
$(document).ready(function() {
    $('#diagAddLang').html({
        //'<form><input type="text" name="locale></form>'
    });
    $('#btnAddLang_').live('click', function(event) {
        event.preventDefault();
        $('#diagAddLang').dialog({
            title: "Add a New Language",
            width: 400,
            height: 300,
            draggable: false,
            modal: true,
            resizable: false,
            buttons: {
                'Add': function() {
                    
                },
                'Cancel': function() {
                    $(this).dialog('close');
                }
            }
        });
    });
});
            /*
            $.confirm({
                'title': 'ADD A NEW LANGUAGE',
                'message': " <strong>YOU WANT TO DELETE </strong><br /><font color=red>' " + name + " ' </font> ",
			'buttons': { 
				'Yes': {
					'class': 'special',
					'action': function() {
						window.location = href;
					}
				},
				'No' : {
					'class'	: '',
					'action': function() {
					}
				}
			}
               
           
	});
            /* Init DataTables */
           // var oTable = $('#example').dataTable();

            /* Apply the jEditable handlers to the table */
            /*
            $('td', oTable.fnGetNodes()).editable( '../examples_support/editable_ajax.php', {
                    "callback": function( sValue, y ) {
                            var aPos = oTable.fnGetPosition( this );
                            oTable.fnUpdate( sValue, aPos[0], aPos[1] );
                    },
                    "submitdata": function ( value, settings ) {
                            return {
                                    "row_id": this.parentNode.getAttribute('id'),
                                    "column": oTable.fnGetPosition( this )[2]
                            };
                    },
                    "height": "14px"
            });
            */

</script>
