<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">CARRIERE</div>
                <div class="subtitle">PRODUIRE EN PROPRE POUR FIABILISER NOS PRESTATIONS</div>
                <div class="text">
                    <p>La stratégie de l’entreprise repose sur le talent de nos équipes. Notre culture d’entreprise tire sa principale force de l’engagement, de la réactivité et de la performance de ces dernières. Elle se traduit sur le terrain avec des Managers impliqués et engagés dans le développement personnel et professionnel des collaborateurs.</p>
                    <p>Notre politique RH a axé sa démarche sur :</p>
                    <ul class="dot bigger_padding">
                        <li><strong>L’Excellence</strong> :
                            <p>Par leur fiabilité et leur expertise, les hommes et les femmes de Naviland Cargo assurent au quotidien notre excellence sur le terrain et sont créateurs de valeur pour nos clients.</p>
                        </li>
                        <li><strong>La Performance :</strong>
                            <p>Nos équipes sont engagées dans le progrès continu avec la mise en œuvre de standard de pilotage de l’activité et de la qualité, le programme « Cap Performance ».</p>
                        </li>
                        <li><strong>La Responsabilité :</strong>
                            <p>Notre organisation décentralisée, selon nos différentes activités et implantations géographiques, repose sur la responsabilisation de nos collaborateurs. Celle-ci se traduit par une volonté de déléguer à tous les niveaux.</p>
                        </li>
                    </ul>
                    <p>Naviland Cargo est l’alternative verte «au tout route» sur longue distance et un acteur majeur de l’expansion du combiné rail-route en Europe. Elle propose à ses collaborateurs de travailler dans un environnement international avec des métiers divers et variés :</p>
                    <ul class="dash bigger_padding">
                        <li>Chef de projets ferroviaires</li>
                        <li>Responsable commercial</li>
                        <li>Ingénieur Bureau d’études</li>
                        <li>Conducteur de trains</li>
                        <li>Conducteur de dessertes ferroviaires</li>
                        <li>Coordinateur de dessertes ferroviaires</li>
                        <li>Chef d’équipe terminal</li>
                        <li>Conducteur d’engins de manutention (portique, autogrue…)</li>
                        <li>Affréteur routier</li>
                        <li>Assistant MOA du système d’information</li>
                        <li>Agent de recouvrement</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>