<div class="widget">
	<div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('Add New') ?></span></div>
	<div class="content">
		<form enctype="multipart/form-data" name="formLinkCategories" id="formLinkCategories" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
			<div class="section" >
	        	<label><?php echo $this->translate('Name') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
	            <div><?php echo $this->form->name; ?></div>
	        </div>
			<div class="section">
	        	<label><?php echo $this->translate('Description') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
	            <div><?php echo $this->form->description; ?></div> 
	        </div>
	        <div class="section last">
				<div><a class="uibutton submit_form" ><?php echo $this->translate('Submit') ?></a></div>
			</div>		
		</form>
	</div>	
</div>