<div class="widget" >
	<div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('Link Categories') ?></span></div>
	<div class="content">
		<div id="UITab">
			<ul class="tabs" >
				<li ><a href="#tab2"><?php echo $this->translate('List of Categories') ?></a></li>            
			</ul>
			<div class="tab_container">
				<div id="tab2" class="tab_content"> 
					<div class="load_page">
						<ul class="uibutton-group">
							<li><a href="<?php echo $this->url(array('action' => 'addLinkCategory')); ?>" class="uibutton icon add"><?php echo $this->translate('Add New Category') ?></a></li>
						</ul>
						<div class="tableName toolbar">
							<h3>List</h3>
							<table class="display data_table2">
								<thead>
									<tr>
                						<th><?php echo $this->translate('Name') ?></th>
                						<th><?php echo $this->translate('Description') ?></th>
                						<th><?php echo $this->translate('Actions') ?></th>
									</tr>
								</thead>
								<tbody>
									<?php foreach ($this->link_categories as $cat) { ?>
									<tr>
										<td><?php echo $cat->name;?></td>
						        		<td><?php echo $cat->description; ?></td>
						        		<td class="center">
						        			<span class="tip"><a href="<?php echo $this->url(array('action' => 'editCat', 'id' => $cat->link_category_id), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
											<span class="tip"><a href="<?php echo $this->url(array('action' => 'deleteCat', 'id' => $cat->link_category_id), 'default'); ?>" class="delete" name="<?php echo $this->escape($cat->name); ?>"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>						        			
						        		</td>
									</tr>
									<?php } ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
