<div class="widget">
    <div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('page') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li ><a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'pages', 'action'=>'index'), 'default', true) ?>"><?php echo $this->translate('list of pages') ?></a></li>  
                <li ><a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'pages', 'action'=>'view', 'id'=>$this->page['parent_id']), 'default', true); ?>"><?php echo $this->translate($this->page['parent_name'])?></a></li>  
                <li class="active"><a href="#tab2"><?php echo $this->translate($this->page['name']) ?></a></li>
            </ul>
        <form enctype="multipart/form-data" name="form[ages" id="formPages" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <?php echo $this->form->page_id; ?>
            <div class="section">
                <label><?php echo $this->translate('french') . ' ' . $this->translate('content') ?></label>   
                <div>&nbsp;<?php echo $this->form->content; ?></div>
            </div>
            <div class="section">
                <label>ENGLISH <?php echo $this->translate('content') ?></label>   
                <div><?php echo $this->form->content_en; ?></div>
            </div>
            <div class="section last">
                <div><a class="uibutton submit_form" ><?php echo $this->translate('submit') ?></a></div>
            </div>
        </form>
        </div>
    </div>	
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('ul.tabs li:first').removeClass('active');
	});
</script>