<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('pages') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li ><a href="#tab2"><?php echo $this->translate('list of pages') ?></a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="jobs">
                                <thead><tr><th><?php echo $this->translate('pages')?></th></tr></thead>
                                <tbody>
                                    <?php foreach($this->pages as $page): ?>
                                    <tr>
                                        <td>
                                            <a href="<?php echo $this->url(array('module'=> 'admin', 'controller'=>'pages', 'action' =>'view', 'id' => $page->page_id), 'default', true); ?>">
                                                <?php echo $this->translate(strtoupper($page->name)); ?>
                                            </a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
