<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('pages') ?></span></div>
    <div class="content">
        <?php if ($this->pages && $this->pages[0]) { ?>
        <div id="UITab">
            <ul class="tabs" >
                <li ><a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'pages', 'action'=>'index'), 'default', true) ?>"><?php echo $this->translate('list of pages') ?></a></li>  
                <li class="active"><a href="#tab2"><?php echo $this->translate(strtoupper($this->pages[0]['parent_name'])) ?></a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="jobs">
                                <thead>
                                    <tr>
                                        <th>page</th>
                                        <th>parent page</th>
                                        <th>action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <?php foreach($this->pages as $page): ?>
                                        <tr>
                                        <td><?php echo $this->translate($page['name']); ?></td>
                                        <td><?php echo $this->translate(strtoupper($page['parent_name'])); ?></td>
                                            <td class="center">
                                                <span class="tip"><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $page['page_id']), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <?php } ?>
    </div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('ul.tabs li:first').removeClass('active');
	});
</script>