<div class="widget">
    <div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('job categories') ?></span></div>
    <div class="content">
        
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/jobcategories"><?php echo $this->translate('list of job categories') ?></a></li>   
                <li class="active"><a href="#"><?php echo $this->translate('add a job category') ?></a></li>          
            </ul>
            <div class="tab_container">
            </div>
        </div>
        
        <form enctype="multipart/form-data" name="formJobCategories" id="formJobCategories" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <div class="section" >
                <label><?php echo $this->translate('name') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->name; ?></div>
            </div>
            <div class="section last">
                <div><a class="uibutton submit_form" ><?php echo $this->translate('submit') ?></a></div>
            </div>
        </form>
    </div>	
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('ul.tabs li:first').removeClass('active');
});
</script>