<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('job categories') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li ><a href="#tab2"><?php echo $this->translate('list of job categories') ?></a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a Job Category"><?php echo $this->translate('add a job category')?></a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="jobs">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate('Name')?></th>
                                        <th><?php echo $this->translate('Actions')?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->job_categories as $job_category): ?>
                                    <tr>
                                        <td><?php echo $job_category->name;?></td>
                                        <td class="center">
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $job_category->job_category_id), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $job_category->job_category_id), 'default'); ?>" class="delete" name="<?php echo $this->escape($job_category->name); ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>						        			
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
