<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Film Animation</div>
                <div class="text">
                    <p>Il s'agit d'une animation de 2 à 3 minutes maximum dont le but est de présenter Naviland Cargo à travers son savoir faire, ses valeurs et ses ambitions. </p>
                </div>
            </div>
        </div>
    </div>
 </div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>