<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
            <div class="title">OPÉRATEUR<br>DE TRANSPORT COMBINÉ</div>
            <div class="subtitle">UNE VISION CONTEMPORAINE DU TRANSPORT</div>
            <div class="text">
                <p>Leader européen du transport combiné maritime, Naviland Cargo 
                    exerce les missions d’opérateur et commissionnaire de transport en 
                    associant les modes ferroviaires et routiers (ou barges) en une seule 
                    et même chaîne logistique. Nous organisons pour le compte de nos 
                    clients des acheminements avec des ressources propres appuyées par un 
                    réseau de sous traitants. Le plan de transport de Naviland Cargo 
                    s’articule autour de l’ensemble des ports majeurs en France et en 
                    Europe et notamment : les ports maritimes du Havre et de Marseille, 
                    Fos, Anvers, Rotterdam et Barcelone vers les pôles économiques ou 
                    industriels que sont Paris, Lyon, Strasbourg, Toulouse, Bordeaux, 
                    Lille, Ludwigshafen.</p>

                <p>Notre cœur de marché est le transport et la logistique de conteneurs maritimes, caisses mobiles, citernes, etc. , sur des trains ouverts à l’ensemble de notre clientèle, ou dédiés pour certains projets :</p>
                <ul class="checkmark">
                    <li>Transport Combiné associant les modes ferroviaires et routiers en une seule et même chaîne logistique (One Stop Shop)</li>
                    <li>Transport de conteneurs maritimes, caisses mobiles, citernes, vrac, etc.</li>
                    <li>Transport de terminal à terminal ou Door to Door</li>
                    <li>Trains réguliers, aller et retour, dédiés</li>
                    <li>Trains spots</li>
                    <li>Transport routier intégral avec NAVITRUCKING</li>
                    <li>Stockage, maintenance des conteneurs </li>
                    <li>Procédure Ferro Maritime (transport de conteneurs sous douane)</li>
                </ul>

                <div class="subtitle2">UN ENGAGEMENT DE QUALITE ET DE NEUTRALITE</div>

                <p>Parmi nos clients, nous comptons 65% de compagnies maritimes, agents maritimes 
                    et transitaires, 20% de citerniers et 15% de chargeurs en direct, à l’import et 
                    à l’export. La relation de confiance développée avec notre clientèle favorise le 
                    dialogue et la mise en œuvre de solutions de transport adaptées en fonction de besoins 
                    spécifiques.
                </p>
                
                <div class="subtitle2">INTERNATIONALISATION ET INNOVATION</div>

                <p>Présent dans les principaux ports européens (Marseille/Fos, Le Havre, Barcelone, Zeebrugge, Anvers, Rotterdam…), nous sommes depuis 2010 engagés dans l’internationalisation de 
                notre offre de service. Cette stratégie de développement s’est traduite ces dernières années par  de nouvelles implantations,  au Benelux, en  Espagne et en Allemagne.</p>
                
                <div class="subtitle2">LE COMBINE, UN MODE DE TRANSPORT ECOLOGIQUE ET DURABLE</div>

                <p>De plus en plus sensibles à la réduction des émissions de C02, nos clients exigent un transport 
                    propre. Dans ce contexte éco-responsable, le transport combiné constitue une solution durable 
                    par les gains substantiels qu’il procure en termes d’économie d’énergie et de limitation de 
                    l’effet de serre. Les bénéfices offerts par ce mode de transport à la collectivité ont été 
                    valorisés par les mesures réglementaires françaises du Grenelle de l’Environnement qui incitent 
                    à son utilisation.
                </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>