<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Gestionnaire de Terminal</div>
                <div class="subtitle">Des terminaux pour la massification et l’équilibre des flux</div>
                <div class="text">
                    <p>Parallèlement à notre activité d’opérateur de transport, nous sommes à travers notre réseau de terminaux un véritable soutien logistique intégré pour nos clients. Notre offre terminalistique apporte une réelle valeur ajoutée aux clients en recherche de  massification et d’équilibre de leurs flux pour une gestion optimisée du transport. </p>
                    <p>Ainsi, sur les terminaux Naviland Cargo, vous bénéficiez des activités et prestations suivantes :</p>
                    <div class="ul_title">Les opérations de chantier (non ferroviaires)</div>
                    <ul class="circle">
                         <li>Prestation de MANUTENTION entre le mode de transport ferroviaire et le mode de transport routier, </li>
                         <li>GESTION DE STOCK de conteneurs sous douane ou non</li>
                         <li>REPARATION / PREPARATION de conteneurs</li>
                         <li>GESTION DU STATIONNEMENT des conteneurs et des ensembles routiers</li>
                         <li>EDI : Les échanges d’informations avec les clients sur l’état des stocks</li>
                         <li>Les déclarations officielles ou formalités douanières éventuelles liées au statut MADT (Magasins et Aires de Dédouanement Temporaire) des terminaux</li>
                    </ul>
                    <div class="ul_title">Les opérations terminalistiques (non ferroviaires)</div>
                    <ul class="circle">
                        <li>DESSERTE des trains du point où le tractionnaire ferroviaire les met à disposition (triage) jusqu’aux infrastructures c'est-à-dire les cours de transbordement sur lesquelles s’effectuent les opérations de manutention (et réciproquement),</li>
                        <li>TRI de wagons en fonction des compositions de rames demandées,</li>
                        <li>Opérations de formations des trains à la demande des entreprises ferroviaires</li>
                    </ul>
                    <div class="ul_title">La sécurité</div>
                    <ul class="circle">
                        <li>Mesures spécifiques liées au transfert de marchandises dangereuses</li>
                        <li>Interface avec les entreprises ferroviaires (notamment entrées et sorties de train)</li>
                    </ul>
                    <img src="/medias/images/illustrations/metiers_platform.jpg">
                </div>
            </div>
        </div>
    </div>
 </div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>