<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Traction ferroviaire</div>
                <div class="subtitle">PRODUIRE EN PROPRE POUR FIABILISER NOS PRESTATIONS</div>
                <div class="text">
                    <p>
                        Naviland Cargo opère sa propre traction ferroviaire au moyen de locomotives 
                        dédiées, de wagons et de ses propres conducteurs de trains.
                    </p>
                    <p>
                        Le département des activités ferroviaires de Naviland Cargo est garant de la 
                        performance de ses trains avec un taux de fiabilité de 96%. Doté de moyens 
                        modernes en termes de production et de suivi informatisé, il assure en propre 
                        la production du plan de transport proposé aux clients avec plus de 500 trains 
                        mensuels grâce à ses équipes de conducteurs et son parc de locomotives.
                    </p>
                    <p>
                        Dans ce département on retrouve le Pôle Train basé au Havre dédié au suivi et à 
                        la coordination des convois et ceci 24h/24 et 6j/7. C’est avec ce service et grâce 
                        à l’engagement des personnes qui le composent que Naviland Cargo est devenue une 
                        entreprise reconnue pour la qualité de ses prestations et pour la recherche de solutions 
                        innovantes pouvant apporter de réelles plus-values à ses clients et partenaires.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>