<div class="widget">
    <div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('implantations') ?></span></div>
    <div class="content">
        
        <form enctype="multipart/form-data" name="formImplantations" id="formImplantations" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <?php echo $this->form->implantation_id; ?>
            
            <div class="section">
                <label><?php echo $this->translate('title') ?></label>   
                <div><?php echo $this->form->title; ?></div>
            </div>
            <div class="section">
                <label><?php echo $this->translate('subtitle') ?></label>   
                <div><?php echo $this->form->subtitle; ?></div>
            </div>
            <div class="section">
                <label><?php echo $this->translate('content') ?></label>   
                <div><?php echo $this->form->content; ?></div>
            </div>
            <div class="section last">
                <div><a class="uibutton submit_form" ><?php echo $this->translate('submit') ?></a></div>
            </div>
        </form>
    </div>	
</div>

<script type="text/javascript">
$(function() {
});
</script>
