<div class="widget" >
	<div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('implantations') ?></span></div>
	<div class="content">
		<div id="UITab">
			<ul class="tabs">
				<li ><a href="#tab2"><?php echo $this->translate('list of implantations') ?></a></li>            
			</ul>
			<div class="tab_container">
				<div id="tab2" class="tab_content"> 
					<div class="load_page">
						<div class="tableName toolbar">
							<h3><?php echo $this->translate('list') ?></h3>
							<table class="display data_table2" id="jobs">
								<thead>
									<tr>
										<th><?php echo $this->translate('implantation') ?></th>
									</tr>
								</thead>
								<tbody>
                                                                    <?php if ($this->implantations) { ?>
                                                                        <?php foreach($this->implantations as $implantation) { ?>
									<tr>
                                                                            <td><a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'implantations', 'action'=> strtolower($implantation['name']), 'id'=>$implantation["implantation_id"]), 'default', true)?>"><?php echo $implantation['display_name'] ?></a></td>
                                                                        </tr>
                                                                        <?php } ?>
                                                                    <?php } ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#language').change(function(){
            if ($(this).val() == 'all')
                window.location.href='<?php echo $this->url(array('module'=>'admin', 'controller' => 'jobs', 'action'=>'index'), 'default', true); ?>'
            else
                window.location.href='<?php echo $this->url(array('module'=>'admin', 'controller' => 'jobs'), 'default', true); ?>/'+$(this).val();		
        })
    })
</script>