<div id="dashboard">
    
    <!--
    <div class="widget">
         
        <div class="header"><span><span class="ico gray stats_lines"></span>Statistiques</span></div>
        <div class="content"> <br class="clear">

           
            <div class="widgets">
                <div class="oneThree">
                    <a href=""><div class="shoutcutBox" style="left: 0px; "> <span class="ico color group"></span> <strong style="color: black;"><?php echo $this->pplCount ?></strong> <em>utilisateurs inscrits</em> </div></a>
                    <div class="breaks"><span></span></div>

                </div>

                <div class="clear"></div>

            </div>
           
        </div>
     -->
    </div>