<div id="dashboard">
    
    
    <div class="widget">
        <div class="header"><span><span class="ico gray stats_lines"></span>Statistiques</span></div>
        <div class="content"> <br class="clear">


                                <!-- Third / Half column-->
            <div class="widgets">
                <div class="oneThree">
                    <a href="<?php echo $this->url(array('controller' => 'jobs')); ?>"><div class="shoutcutBox" style="left: 0px; "> <span class="ico color group"></span> <strong style="color: black;"><?php echo $this->pplCount ?></strong> <em>utilisateurs inscrits</em> </div></a>
                    <div class="breaks"><span></span></div>

                </div>

                <!-- clear fix -->
                <div class="clear"></div>

            </div><!-- End content -->
        </div>
    
    </div>