<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation d'Anvers</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>37, Rijnkaai</li>
                                    <li>2000 ANVERS (BELGIQUE)</li>
                                    <li>tél. > + 32 (0) 3.205.73.45</li>
                                    <li>fax > + 32 (0) 3.227.57.96</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mr Boudewijn VAN THILLO</li>
                                    <li>tél. > + 32 (0) 3.205.73.45</li>
                                    <li>fax > + 32 (0) 3.227.57.96</li>
                                    <li>email: bvanthillo@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>08H00 à 18H00</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>L’agence d’Anvers organise l’expédition et réception de conteneurs sur les terminaux portuaires du Mainhub(IFB) , Noordzee Quai 913(PSA) et Combinant 755 à Anvers ainsi  que sur les terminaux portuaires CHZ, APMT et NSF à Zeebrugge.</li>
                                <li>L’agence NAVILAND CARGO de Lyon-Vénissieux est certifiée ISO 9001 et ISO 14001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI à l’Import et l'Export</li>
                                    <li>Enlèvement et livraison par route, barges ou Narcon (navette ferroviaire)</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="right">
                                    <li>Anvers (PSA Quai 913) ↔ Vénissieux / Fos / Marseille / Barcelone</li>
                                    <li>Anvers (IFB MainHub) ↔ Strasbourg</li>
                                    <li>Anvers (Combinant) ↔ Dourges / Vénissieux/ Fos / Marseille/Valenton / Bodreaux</li>
                                    <li>Zeebrugge (CHZ/APM/NSF) ↔ Dourges/Vénissieux / Fos / Marseille / Barcelone</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>