<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Bordeaux</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>40-45 rue Radio Londres</li>
                                    <li>33130 BEGLES</li>
                                    <li>tél. > + 33(0) 5.56.49.81.50</li>
                                    <li>fax > + 33(0) 5.56.85.33.56</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>M. Jean Luc BORT</li>
                                    <li>tél. > + 33(0) 5.56.49.34.36</li>
                                    <li>fax > + 33(0) 5.56.85.81.78</li>
                                    <li>email: jlbort@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du lundi au Vendredi <strong>de 07h à 19h</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <li>Le terminal de Bordeaux est situé hors agglomération, en bordure de la rocade de Bordeaux, sur les communes de Bègles et de Villenave d’Ornon. Il s’agit d’un terminal rail-route d’une surface de 11 ha constitué de 2 cours à portique et d’1 cour à grue.</li>
                            <li>Il est accessible pour les clients par la E05/E70 sortie n°20.</li>
                            <li>L’agence NAVILAND CARGO de Bordeaux est certifiée ISO 9001  et ISO 14001. </li>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Réalisation des opérations de dessertes ferroviaires</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Réparation de conteneurs</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <ul>
                                <li>Bordeaux ↔ Toulouse / Fos / Marseille</li>
                                <li>Bordeaux ↔ Le Havre</li>
                                <li>Bordeaux ↔ Valenton / Dourges / Anvers / Zeebruges</li>
                            </ul>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>