<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title"><?php echo $this->implantation['title'] ?></div>
                <div class="subtitle"><?php echo $this->implantation['subtitle'] ?></div>
                <div class="text">
                    <p>Le Centre National des Opérations ouvert 24h/24, 6j/7, assure le suivi opérationnel de nos trains, réagit aux aléas de production, met en œuvre des solutions alternatives et vous informe en temps réel.</p>
                    <p>Pour garantir une maîtrise complète de l’ensemble de la chaîne de transport, le CNO véritable centre névralgique de Naviland Cargo, est organisé en deux grands pôles complémentaires et orientés <strong>satisfaction client</strong>:</p>
                    <div class="ul_title">Le Pôle Commandes qui assure l’activité de call center et de SAV:</div>
                    <ul class="circle">
                        <li>Prise de réservations</li>
                        <li>Proposition de solutions répondant aux critères de coût, qualité et délais</li>
                        <li><strong>Optimisation</strong> et massification des trains</li>
                        <li>Relation avec les douanes</li>
                        <li><strong>Information client</strong> à travers notre système Aviso de chaque étape du transport</li>
                        <li><strong>Interface client</strong> en cas d’aléas</li>
                    </ul>
                    <div class="ul_title">Le Pôle Trains dont la fonction principale est l’organisation de la production ferroviaire nationale et internationale</div>
                    <ul class="circle">
                        <li>Gestion des moyens (agents de conduite et locomotives)</li>
                        <li>Gestion des sillons</li>
                        <li>Planification et suivi des acheminements ferroviaires</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>