<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Cognac</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>14 Place de la Gare</li>
                                    <li>16100 COGNAC</li>
                                    <li>tél. > + 33 (0) 5.45.81.00.06</li>
                                    <li>fax > + 33 (0) 5.45.80.53.37</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mme Lydie MAINGENAUD</li>
                                    <li>tél. > +33 (0) 5.56.49.81.62</li>
                                    <li>fax > +33 (0) 5.56.85.81.78</li>
                                    <li>email: lmainguenaud@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du lundi au Vendredi <strong>de 8h à 17h</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <li>Le terminal de Cognac est situé en agglomération sur la commune de Cognac. Il s’agit d’un terminal rail-route d’une surface de 1500 m² constitué d’une cour à portique et d’une cour à grue.</li>
                            <li>Il est accessible pour les clients depuis la E603/N141 en empruntant la D945.</li>
                            <li>L’agence NAVILAND CARGO de Cognac est certifiée ISO 9001  et ISO 14001.</li>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Cognac ↔ Le Havre</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>