<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Fos</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Secteur 86 - Centre Tertiaire</li>
                                    <li>Zone Portuaire de Service</li>
                                    <li>Z.I. de Fos sur Mer</li>
                                    <li>13516 Port Saint Louis du Rhône Cedex</li>
                                    <li>tél. > +33 (0) 4.91.10.15.08</li>
                                    <li>fax > +33 (0) 4.42.48.90.13</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mr Véronique BEAUCHAMPS</li>
                                    <li>tél. > +33 (0) 4.91.10.15.08</li>
                                    <li>fax > +33 (0) 4.91.02.25.40</li>
                                    <li>email: vbeauchamps@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>06h30 à 17h30</strong></li>
                        </ul>
                    </div>
                </div>
                
                        
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Les terminaux de Fos desservis avec le plan de transport de Naviland Cargo sont situés dans les enceintes du Grand Port Maritime de Marseille :</li>
                                <li>-  2  embranchements portuaires: Seayard & Eurofos.</li>
                                <li>-  1 embranchement avec 1 aire de stockage d’UTI (EP réparateurs)</li>
                                <li>L’agence NAVILAND CARGO de Fos est certifiée ISO 9001 et ISO 14 001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Organisation des opérations de dessertes ferroviaires dans le domaine portuaire</li>
                                    <li>Enlèvement et livraison par route</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Stockage d’UTI vides</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Fos ↔ Bordeaux</li>
                                    <li>Fos ↔ Toulouse</li>
                                    <li>Fos ↔ Lyon-Vénissieux</li>           
                                    <li>Fos ↔ Strasbourg</li>
                                    <li>Fos ↔ Anvers</li> 			
                                    <li>Fos ↔ Le Havre</li>
                                    <li>Fos ↔ Zeebrugge</li>                   
                                    <li>Fos ↔ Ludwigshafen</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>