<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Gevrey</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Chemin des Etangs</li>
                                    <li>21160 PERRIGNY LES DIJON</li>
                                    <li>tél. > +33 (0) 3.80.35.71.70</li>
                                    <li>fax > +33 (0) 3.80.35.71.96</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mr Frédéric MEGE</li>
                                    <li>tél. > +33 (0) 4.72.21.51.58</li>
                                    <li>fax > +33 (0) 4.72.50.20.76</li>
                                    <li>email: fmege@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi <strong>de 7h30 à 18h00</strong></li>
                        </ul>
                    </div>
                </div>
                
                        
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Le terminal est situé sur la commune de Perrigny-lès-Dijon. Il s’agit d’un terminal rail-route d’une surface de 2 ha, possédant 1050 m de voies ferrées et constitué d’une cour à grue et d’une cour à portique.  Le terminal est accessible pour les clients depuis l’A311 (sortie Terminal Rail-Route).</li>
                                <li>L’agence NAVILAND CARGO de Gevrey est certifiée ISO 9001 et ISO 14001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Gevrey ↔ Le Havre</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>