<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title"><?php echo $this->implantation['title'] ?></div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li><?php echo $this->implantation['address'] ?></li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li><?php echo $this->implantation['service_address'] ?></li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li><?php echo $this->implantation['hour'] ?></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <li><?php echo $this->implantation['general'] ?></li>
                        </ul>
                        <ul id="implantation_activities">
                            <li>Domaines d’activités</li>
                            <li><?php echo $this->implantation['activities'] ?></li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li><?php echo trim($this->implantation['acceptance'], " \t\n\r"); ?></li>
                        </ul>
                        <ul id="implantation_rails">
                            <li>Liaisons ferroviaires</li>
                            <li><?php echo $this->implantation['rails'] ?></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>