<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Le Havre Terminaux</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Bâtiment du Port autonome</li>
                                    <li>Quai de l‘Europe</li>
                                    <li>76600 LE HAVRE</li>
                                    <li>tél. > +33 (0) 2.35.53.17.47</li>
                                    <li>fax > +33 (0) 2.35.25.38.13</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mme Odile LEVALLOIS</li>
                                    <li>tél. > +33 (0) 2.35.25.80.62</li>
                                    <li>fax > +33 (0) 2.35.26.06.65</li>
                                    <li>email: olevallois@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>8h00 à 17h30</strong></li>
                        </ul>
                    </div>
                </div>
                
                        
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Au Havre, NAVILAND CARGO dessert les principaux terminaux portuaires du Grand Port Maritime du Havre :</li>
                                <li> - Atlantique</li>
                                <li> - Europe</li>
                                <li> - Océan</li>
                                <li> - Normandie</li>
                                <li> - TDF</li>
                                <li> - TPO</li>
                                <li>L'agence NAVILAND CARGO du Havre est certifiée ISO 9001 et ISO 14 001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Organisation des opérations de dessertes ferroviaires dans le domaine portuaire</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Le Havre ↔ Bordeaux </li>
                                    <li>Le Havre ↔ Lyon-Vénissieux </li>
                                    <li>Le Havre ↔ Cognac</li>
                                    <li>Le Havre ↔ Strasbourg </li>
                                    <li>Le Havre ↔ Anvers </li>
                                    <li>Le Havre ↔ Gevrey</li>
                                    <li>Le Havre ↔ Paris-Valenton</li>
                                    <li>Le Havre ↔ Ludwigshafen </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>