<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Lyon-Vénissieux</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Chemin du charbonnier</li>
                                    <li>69200 VENISSIEUX</li>
                                    <li><strong>Adresse postale</strong></li>
                                    <li>BP 587</li>
                                    <li>69969 CORBAS Cédex</li>
                                    <li>tél. > +33 (0) 4.72.21.51.00</li>
                                    <li>fax > +33 (0) 4.72.50.81.01</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mr Frédéric MEGE</li>
                                    <li>tél. > +33 (0) 4.72.21.51.58</li>
                                    <li>fax > +33 (0) 4.72.50.20.76</li>
                                    <li>email: fmege@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>5H15 à 19H45</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Le terminal de Lyon-Vénissieux est situé en agglomération sur les communes de Vénissieux et Saint-Priest. Il s’agit d’un terminal rail-route d’une surface de 07 ha environ constitué de 4 cours à grue et de 3 cours à portique, ainsi que de 2 aires de stockage/réparation des UTI. Le terminal est accessible pour les clients par la rocade Est (contournement Est de Lyon par l’A46) Sortie 13.</li>
                                <li>L’agence NAVILAND CARGO de Lyon-Vénissieux est certifiée ISO 9001 et ISO 14001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Réalisation des opérations de dessertes ferroviaires</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Réparation de conteneurs</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Lyon ↔ Fos</li>
                                    <li>Lyon ↔ Anvers/Zeebrugge </li>
                                    <li>Lyon ↔ Le Havre </li>
                                    <li>Lyon ↔ Strasbourg/Ludwigshafen</li>
                                    <li>Lyon ↔ Barcelone</li>
                                    <li>Lyon ↔ Marseille </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>