<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Marseille</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Bâtiment du Port autonome</li>
                                    <li>Gare du Canet</li>
                                    <li>29 boulevard Ferdinand Lesseps</li>
                                    <li>13309  MARSEILLE CEDEX 14</li>
                                    <li>tél. > +33 (0) 4.91.10.15.40</li>
                                    <li>fax > +33 (0) 4.91.10.15.40</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mr Véronique BEAUCHAMPS</li>
                                    <li>tél. > +33 (0) 4.91.10.15.08</li>
                                    <li>fax > +33 (0) 4.91.02.25.40</li>
                                    <li>email: vbeauchamps@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>5H00 à 18H30</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Le terminal de Marseille est situé dans les enceintes du Grand Port Maritime de Marseille. Il s’agit d’un terminal rail-route constitué de 2 cours à portiques et d’1 cour à grues. Tous les postes à quai sont connectés au réseau NAVILAND CARGO</li>
                                <li>L’agence NAVILAND CARGO de Lyon-Vénissieux est certifiée ISO 9001 et ISO 14001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et livraison par route</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Stockage d’UTI vides</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Marseille ↔ Bordeaux</li>
                                    <li>Marseille ↔ Toulouse</li>
                                    <li>Marseille ↔ Lyon-Vénissieux</li>            
                                    <li>Marseille ↔ Strasbourg</li>
                                    <li>Marseille ↔ Paris-Valenton</li>               
                                    <li>Marseille ↔ Anvers</li>
                                    <li>Marseille ↔ Zeebrugge</li>                     
                                    <li>Marseille ↔ Ludwigshafen</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>