<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Paris-Valenton</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>1 rue Pierre Sémard</li>
                                    <li>94380 BONNEUIL SUR MARNE</li>
                                    <li>tél. > + 33 (0) 1.43.39.74.59</li>
                                    <li>fax > + 33 (0) 1.49.80.91.14</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mme Lydie MAINGUENAUD</li>
                                    <li>tél. > +33 (0) 5.56.49.81.62</li>
                                    <li>fax > +33 (0) 5.56.85.81.78</li>
                                    <li>email: lmainguenaud@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>06h00 à 18h30</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Le terminal de Paris-Valenton est situé sur la commune de Bonneuil sur Marne. Il s’agit d’un terminal rail-route d’une surface de 10 ha dans lequel Naviland Cargo exploite une cour à portique.</li>
                                <li>ll est accessible pour les clients depuis la N406 ou la RD 60.</li>
                                <li>L’agence NAVILAND CARGO de Paris-Valenton est certifiée ISO 9001  et ISO 14001. </li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Réalisation des opérations de dessertes ferroviaires</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Réparation de conteneurs</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Valenton ↔ Marseille</li>			 
                                    <li>Valenton ↔ Le Havre</li>
                                    <li>Valenton ↔ Dourges</li>			 
                                    <li>Valenton ↔ Bordeaux</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>