<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Strasbourg</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">CONTACTS</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>10 rue du bassin de Commerce</li>
                                    <li>67100 STRASBOURG</li>
                                    <li>tél. > +33 (0) 3.88.56.64.00</li>
                                    <li>fax > +33 (0) 3.88.26.12.10</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commercial</li>
                            <li>
                                <ul>
                                    <li>Mr Christophe BALL</li>
                                    <li>tél.: +33 (0) 3.88.56.64.06</li>
                                    <li>fax: +33 (0) 3.88.26.12.10</li>
                                    <li>mail: cball@naviland-cargo.com</li>  
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>
                                <ul>
                                    <li>Du Lundi au Vendredi <strong>de 6h00 à 20h00</strong></li>
                                    <li>Le Samedi <strong>de 07h00 à 11h00</strong></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <li>Le terminal de Strasbourg est situé dans les enceintes du Port Autonome de Strasbourg (Terminal Nord).</li>
                            <li>L’agence NAVILAND CARGO de Strasbourg est certifiée ISO 9001 et ISO 14001.</li>
                        </ul>
                        <ul>
                            <li>Domaines d'activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Organisation et traitement des Départs & Arrivées d'UTI  à l'Import et l'Export</li>
                                    <li>Enlèvement et livraison par route</li>
                                    <li>Gardiennage d'UTI chargées</li>
                                    <li>Stockage d'UTI vides</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Domaines d'activités</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Strasbourg ↔ Anvers</li> 			
                                    <li>Strasbourg ↔ Ludwigshafen</li>
                                    <li>Strasbourg ↔ Le Havre</li> 		
                                    <li>Strasbourg ↔ Vénissieux</li>
                                    <li>Strasbourg ↔ Barcelone</li>		
                                    <li>Strasbourg ↔ Fos / Marseille</li>
                                </ul>
                            </li>
                        </ul>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');
});
</script>