<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Agence d'Exploitation de Toulouse</div>
                
                <div class="block" id="block_contacts">
                    <div class="block_title">Contacts</div>
                    <div class="block_content">
                        <ul>
                            <li>Adresse</li>
                            <li>
                                <ul>
                                    <li>Route nationale 20</li>
                                    <li>31150 FENOUILLET</li>
                                    <li>13309  MARSEILLE CEDEX 14</li>
                                    <li>tél. > + 33 (0) 5.61.37.51.51</li>
                                    <li>fax > + 33 (0) 5.61.37.18.32</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Service Commerical</li>
                            <li>
                                <ul>
                                    <li>Mme Lydie MAINGUENAUD</li>
                                    <li>tél. > +33 (0) 5.56.49.81.62</li>
                                    <li>fax > +33 (0) 5.56.85.81.78</li>
                                    <li>email: lmainguenaud@naviland-cargo.com</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Heures d'ouverture</li>
                            <li>Du Lundi au Vendredi de <strong>06H30 à 18H30</strong></li>
                        </ul>
                    </div>
                </div>
                
                <div class="block">
                    <div class="block_title">Terminal Conteneur Combiné</div>
                    <div class="block_content">
                        <ul>
                            <li>Général</li>
                            <ul>
                                <li>Le terminal de Toulouse est situé sur la commune de Fenouillet à 12 km de Toulouse. Il s’agit d’un terminal rail-route d’une surface de 11 ha constitué d’une cour à grue.</li>
                                <li>Il est accessible pour les clients par la Nationale 20.<li>
                                <li>L’agence NAVILAND CARGO de Toulouse est certifiée ISO 9001  et ISO 14001.</li>
                            </ul>
                        </ul>
                        <ul>
                            <li>Domaines d’activités</li>
                            <li>
                                <ul class="dash">
                                    <li>Réalisation des  manutentions</li>
                                    <li>Réalisation des opérations de dessertes ferroviaires</li>
                                    <li>Organisation et traitement des Départs & Arrivées d’UTI  à l’Import et l’Export</li>
                                    <li>Enlèvement et la livraison par route</li>
                                    <li>Gestion de parc d’UTI vides</li>
                                    <li>Gardiennage d’UTI chargées</li>
                                    <li>Réparation de conteneurs</li>
                                </ul>
                            </li>
                        </ul>
                        <ul>
                            <li>Marchandises acceptées au transport</li>
                            <li>Toutes marchandises sauf  les animaux vivants, les MD classe 1 et 7 (MD 1.4S acceptée) et les transports sous température dirigée.</li>
                        </ul>
                        <ul>
                            <li>Liaisons ferroviaires</li>
                            <li>
                                <ul class="half">
                                    <li>Toulouse ↔ Bordeaux</li>
                                    <li>Toulouse ↔ Fos / Marseille</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>