<div class="widget">
    <div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('jobs') ?></span></div>
    <div class="content">
        
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/jobs"><?php echo $this->translate('list of jobs') ?></a></li>   
                <li class="active"><a href="#"><?php echo $this->translate('add a job') ?></a></li>          
            </ul>
            <div class="tab_container">
            </div>
        </div>
        
        <form enctype="multipart/form-data" name="formJobs" id="formJobs" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <div class="section">
                <label><?php echo $this->translate('language') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->language; ?></div> 
            </div>
            <div class="section" >
                <label><?php echo $this->translate('Title') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->title; ?></div>
            </div>
            <div class="section">
                <label><?php echo $this->translate('Categories') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->job_category_id; ?></div> 
            </div>
            <div class="section">
                <label><?php echo $this->translate('Description') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->description; ?></div> 
            </div>
            <div class="section">
                <label><?php echo $this->translate('Reference') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->reference; ?></div> 
            </div>	
            <div class="section">
                <label><?php echo $this->translate('Status') ?> <small><?php echo $this->translate('Mandatory') ?>.</small></label>   
                <div><?php echo $this->form->status; ?></div> 
            </div>
            <div class="section last">
                <div><a class="uibutton submit_form" ><?php echo $this->translate('Submit') ?></a></div>
            </div>
        </form>
    </div>	
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('ul.tabs li:first').removeClass('active');
});
</script>