<div class="widget">
    <div class="header"><span ><span class="ico gray window"></span>World</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/translate-taxonomies">Translate Taxonomies</a></li>   
                <li class="active"><a href="#">ADD</a></li>          
            </ul>
                        
            <form enctype="multipart/form-data" name="formTranslateTaxonomies" id="formTranslateTaxonomies" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                <div class="section">
                    <label>Taxo <small>required.</small></label>   
                    <div><?php echo $this->form->tid ?></div>
                </div>

                <div class="section">
                        <label>Locale <small>required.</small></label>   
                        <div><?php echo $this->form->locale ?></div>
                </div>
                            
                <div class="section">
                        <label>Content <small>required.</small></label>   
                        <div><?php echo $this->form->content; ?></div>
                </div>

                <div class="section last">
                        <div><a class="uibutton submit_form" >Submit</a></div>
                </div>

            </form>
        </div>
    </div>
</div>