<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                
                <div class="contacts_block">
                    <div class="title">Siège</div>
                    <ul class="list">
                        <li>15 - 17 Allées de l’Europe</li>
                        <li>92588 Clichy-la-Garenne Cedex</li>
                        <li>Tél.:  + 33 (0)1 41 05 33 01</li>
                        <li>Fax.: + 33 (0)1 40 87 08 20</li>
                        <li>contact@naviland-cargo.com</li>
                    </ul>
                </div>
                
                <div class="contacts_block">
                    <div class="title">Centre National des Opération</div>
                    <ul class="list">
                        <li>Centre de Commerce International</li>
                        <li>182 quai Georges V - BP 1073</li>
                        <li>76062 LE HAVRE Cedex</li>
                        <li>Accès Call Center : 0820 900 013 ou +33 (0)235 25 80 50</li>
                        <li>Pôle National : booking.national@naviland-cargo.com</li>
                        <li>Pôle International : booking.international@naviland-cargo.com</li>
                    </ul>
                </div>
                
                <div class="contacts_block">
                <div class="title">Direction Commerciale</div>
                    <ul class="toggle">
                        <li>Pricing Paris</li>
                        <li><ul><li>+ 33 (0)1 41 05 33 12</li><li>grp_pricing@naviland-cargo.com</li></ul></li>
                        <li>Marseille</li> 
                        <li><ul><li>+33 (0)4 91 10 15 08</li><li>vbeauchamp@naviland-cargo.com</li></ul></li>
                        <li>Lyon</li> 
                        <li><ul><li>+33 (0)4 72 21 51 58</li><li>fmege@naviland-cargo.com</li></ul></li>
                        <li>Le Havre</li> 
                        <li><ul><li>+ 33 (0)2 35 25 80 63</li><li>iricouard@naviland-cargo.com</li></ul></li>
                        <li>Le Havre</li> 
                        <li><ul><li>+ 33 (0)2 35 25 80 62</li><li>olevallois@naviland-cargo.com</li></ul></li>
                        <li>Bordeaux</li> 
                        <li><ul><li>+ 33 (0)5 56 49 34 36</li><li>jlbort@naviland-cargo.com</li></ul></li>
                        <li>Bordeaux</li> 
                        <li><ul><li>+ 33 (0)5 56 49 81 61</li><li>eloubert@naviland-cargo.com</li></ul></li>
                        <li>Strasbourg</li> 
                        <li><ul><li>+ 33 (0)3 88 56 64 06</li><li>cball@naviland-cargo.com</li></ul></li>
                        <li>Anvers</li> 
                        <li><ul><li>+32 (0)3 205 73 45</li><li>bvanthillo@naviland-cargo.com</li></ul></li>
                    </ul>
                </div>
                
                <div class="contacts_block">
                <div class="title">Navitrucking</div>
                    <ul class="toggle">
                        <li>Le Havre:</li>
                        <li><ul><li>+33 (0)2 35 25 00 79</li><li>navitrucking_lehavre@naviland-cargo.com</li></ul></li>
                        <li>Fos</li>
                        <li><ul><li>+ 33(0)4 42 48 92 12</li><li>navitrucking_fos@naviland-cargo.com</li></ul></li>
                        <li>Bordeaux</li>
                        <li><ul><li>+ 33 (0)5 56 49 81 57</li><li>navitrucking_bordeaux@naviland-cargo.com</li></ul></li>
                        <li>Strasbourg</li>
                        <li><ul><li>+ 33 (0)3 88 56 64 13</li><li>navitrucking_strasbourg@naviland-cargo.com</li></ul></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>