<div class="widget">
    <div class="header"><span ><span class="ico gray window"></span>World</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/world">World</a></li>   
                <li class="active"><a href="#">Add</a></li>          
            </ul>
                        
            <form enctype="multipart/form-data" name="formWorld" id="formWorld" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                <div class="section">
                        <label>Name <small>required.</small></label>   
                        <div><?php echo $this->form->name ?></div>
                </div>

                <div class="section">
                        <label>Parent <small>required.</small></label>   
                        <div><?php echo $this->form->parent_id ?></div>
                </div>
                            
                <div class="section">
                        <label>Latitude <small>required.</small></label>   
                        <div><?php echo $this->form->lat; ?></div>
                </div>

                <div class="section">
                        <label>Longitude <small>required.</small></label>   
                        <div><?php echo $this->form->lgt; ?></div>
                </div>
                            
                <div class="section last">
                        <div><a class="uibutton submit_form" >Submit</a></div>
                </div>

                        </form>
                </div>
        </div>
</div>

<script type="text/javascript">
$(function() {
  
        $('#parent_id').change(function(){
                var parent_id = $('#parent_id option:selected').val();
                if (parent_id) {
                         $.ajax({
                                type: "post",
                                dataType: "json",
                                url: "/admin/world/ajax-get-locale-by-wid/id/" + parent_id, 
                                success: function(res) {
                                        alert(res);
                                }
                        });
                }
        });
        
});
</script>