<div class="widget">
        <div class="header"><span ><span class="ico gray window"></span>World</span></div>
        
        <div class="content">
                
                <div id="UITab">
                    
                        <ul class="tabs">
                            <li><a href="/admin/world">World</a></li>   
                            <li class="active"><a href="#">Add</a></li>          
                        </ul>
                        
                        <form enctype="multipart/form-data" name="formWorld" id="formWorld" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
                                
                                <div><?php echo $this->form->wid ?></div>
                                <div class="section">
                                        <label>Title <small>required.</small></label>   
                                        <div><?php echo $this->form->title; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Parent <small>required.</small></label>   
                                        <div><?php echo $this->form->parent_id ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Locale <small>required.</small></label>   
                                        <div><?php echo $this->form->locale; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Latitude <small>required.</small></label>   
                                        <div><?php echo $this->form->lat; ?></div>
                                </div>
                            
                                <div class="section">
                                        <label>Longitude <small>required.</small></label>   
                                        <div><?php echo $this->form->lgt; ?></div>
                                </div>
                            
                                <div class="section last">
                                        <div><a class="uibutton submit_form" >Valider</a></div>
                                </div>

                        </form>
                </div>
        </div>
</div>

<script type="text/javascript">
$(function() {
});
</script>