<div class="widget">
    <div class="header"><span><span class="ico gray window"></span><?php echo $this->translate('news') ?></span></div>
    <div class="content">
        
        <div id="UITab">
            <ul class="tabs">
                <li><a href="/admin/news"><?php echo $this->translate('list of news') ?></a></li>   
                <li class="active"><a href="#"><?php echo $this->translate('add news') ?></a></li>          
            </ul>
            <div class="tab_container">
            </div>
        </div>
        
        <form enctype="multipart/form-data" name="formJobs" id="formJobs" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <div class="section">
                <label><?php echo $this->translate('language') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->language; ?></div> 
            </div>
            <div class="section" >
                <label><?php echo $this->translate('title') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->title; ?></div>
            </div>
            <div class="section">
                <label><?php echo $this->translate('description') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->description; ?></div> 
            </div>
            <div class="section">
                <label><?php echo $this->translate('image') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div class="crop-area">
                        <div class="target"></div>
                        <div id="uploadycrop"></div>
                        <div id="custom-queue" class="custom-queue"></div>
                        <div><?php echo $this->form->crop_coords; ?></div>
                </div>
            </div>
            <div class="section">
                <label><?php echo $this->translate('content') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->content; ?></div> 
            </div>
            <div class="section">
                <label><?php echo $this->translate('release date') ?> <small><?php echo $this->translate('mandatory') ?>.</small></label>   
                <div><?php echo $this->form->rdate; ?></div> 
            </div>
            <div class="section last">
                <div><a class="uibutton submit_form" ><?php echo $this->translate('submit') ?></a></div>
            </div>
        </form>
    </div>	
</div>

<script type="text/javascript">
$(function() {
    $('ul.tabs li:first').removeClass('active');
    var ratio = 524/410;
    var post_id = '<?php echo $this->next_post_id ?>';
    
    // For edit
    var cropCoordsArray = [];
    var cropCoords = $('#crop_coords').html();

    if(cropCoords) {
        var position = JSON.parse(cropCoords);

        ratio = (position.x2 - position.x) / (position.y2 - position.y);

        newImg = $('<img />').attr('src', '<?php echo $this->baseUrl(); ?>/medias/images/uploads/' + position.filename);
        $('.crop-area').find('.target').append(newImg);
        cropCoordsArray = [position.x, position.y, position.x2, position.y2];
    }
                                                
    var startUploadicrop = function() {
        $('.crop-area').find('.target img').Jcrop({
            bgFade: true,
            bgOpacity: .5,
            onChange: function(c) {
                c.filename = position.filename;
                $('#crop_coords').html(JSON.stringify(c));
            },
            onSelect: function(c) {
                c.filename = position.filename;
                $('#crop_coords').html(JSON.stringify(c));
            },
            aspectRatio: ratio,
            setSelect : cropCoordsArray
            },
            function() {
                var bounds = this.getBounds();
                boundx = bounds[0];
                boundy = bounds[1];
                jcrop_api = this;
        });
								
        $("#uploadycrop").uploadify({
            'swf' : '<?php echo $this->baseUrl(); ?>/medias/admin/components/uploadify/uploadify.swf',
            'uploader' : '<?php echo $this->baseUrl(); ?>/medias/admin/components/uploadify/uploadify.php',
            'checkExisting' : '<?php echo $this->baseUrl(); ?>/medias/admin/components/uploadify/check-exists.php',
            'buttonImage' : '',
            'formData' : {'context' : 'news', 'baseurl' : '<?php echo $this->baseUrl(); ?>', 'name':'news_'+ post_id},
            'buttonClass' : 'uibutton',
            'method' : 'POST',
            'multi' : false,
            'auto' : true,
            'fileTypeExts' : '*.jpg;*.gif;*.png',
            'fileTypeDesc' : 'Image Files (.JPG, .GIF, .PNG)',
            'queueID' : 'custom-queue',
            'width' : 80,
            'height' : 16,
            'onUploadSuccess' : function(file) {
                if($('.crop-area .target img').data('Jcrop')) {
                    $('.crop-area .target img').data('Jcrop').destroy();
                }

                showSuccess('Fichier ' + file.name  +' téléchargé', 7000);

                newImg = $('<img />').attr('src', '<?php echo $this->baseUrl(); ?>/medias/images/uploads/' + file.name);
                $('.crop-area').find('.target').html(newImg);

                $('.crop-area').find('.target img').Jcrop({
                        bgFade:     true,
                        bgOpacity: .5,
                        onChange: function(c) {
                                c.filename = file.name;
                                $('#crop_coords').html(JSON.stringify(c));
                        },
                        onSelect:  function(c) {
                                c.filename = file.name;
                                $('#crop_coords').html(JSON.stringify(c));
                        },
                        aspectRatio: ratio
                }, function() {
                        var bounds = this.getBounds();
                        boundx = bounds[0];
                        boundy = bounds[1];
                        jcrop_api = this;
                        var  x1=(boundx -240)/2;
                        var  y1=(boundy -180)/2;
                        var  x2=(x1 +240);
                        var  y2=(y1 +180);
                        jcrop_api.animateTo([x1,y1,x2,y2]);
                });
            },
            'onUploadError' : function(file, errorCode, errorMsg, errorString) {
                showError('Erreur de téléchargement du fichier ' + file.name, 7000);
            }
        });
    };
    startUploadicrop();
});
</script>
