<div class="error-msg"><?php if ($this->error_message) echo $this->error_message[0] ?></div>
<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>World</span></div>
        <div class="content">
                <div id="UITab">
                        <ul class="tabs" >
                                <li class="active"><a href="/admin/world">World</a></li>            
                        </ul>
                        <div class="tab_container">
                                <div id="tab2" class="tab_content"> 
                                    <div class="load_page">
                                            <ul class="uibutton-group">
                                                    <li><a href="/admin/world/add" class="uibutton icon add" title="Add">Add</a></li>
                                            </ul>
                                    <div class="tableName toolbar">
                                        <h3><?php echo $this->translate('list') ?></h3>
                                        <table class="display data_table2" id="world" width="100%">
                                            <thead>
                                                <tr>
                                                    <th>Translate World ID</th>
                                                    <th>World ID</th>
                                                    <th>World</th>
                                                    <th>Locale</th>
                                                    <th>Parent</th>
                                                    <th>Latitude</th>
                                                    <th>Longitude</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach($this->focusRowArray as $row): ?>
                                                    <tr>
                                                        <td><?php echo $row['tr_wid'] ?></td>
                                                        <td><?php echo $row['wid'] ?></td>
                                                        <td><?php echo $row['title'] ?></td>
                                                        <td><?php echo $row['locale'] ?></td>
                                                        <td><?php echo $row['parent'] ?></td>
                                                        <td><?php echo $row['lat'] ?></td>
                                                        <td><?php echo $row['lgt'] ?></td>
                                                        <td><a href="/admin/world/add-locale/id/<?php echo $row['tr_wid'] ?>">Add Locale</a></td>
                                                                            <!--
                                        <td><a href="<?php echo $this->url(array('action'=>'view', 'id'=>$row['wid'])) ?>"><?php echo ucwords($row['title']);?></a></td>
                                        <td class="center">
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'edit', 'wid' => $row['tr_wid']), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'delete', 'wid' => $row['tr_wid']), 'default'); ?>" class="delete" name="<?php echo $this->escape($row['title']) ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>		
                                        </td>
                                                                                                                -->

                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
