<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('world') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs">
                <li><a href="<?php echo $this->url(array('controller'=>'world', 'action' => 'index', 'module' => 'admin'), 'default', true) ?>"><?php echo $this->translate('world') ?></a></li> 
                <li class="active"><a href="#tab2"><?php echo $this->id ?></a></li>
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <!--
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title=""><?php echo $this->translate('') ?></a></li>
                        </ul>
                        -->
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="world" width="100%">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate('Title') ?></th>
                                        <th><?php echo $this->translate('Locale') ?></th>
                                       <!-- <th><?php echo $this->translate('Action') ?></th> -->
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->focusRowArray as $row): ?>
                                    <tr>
                                        <td><a href="<?php echo $this->url(array('action'=>'view', 'id'=>$row['wid'])) ?>"><?php echo ucwords($row['title']);?></a></td>
                                        <td><?php echo $row['locale'] ?></td>
                                    <!--    <td class="center">
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'edit', 'wid' => $row->wid), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'delete', 'wid' => $row->wid), 'default'); ?>" class="delete" name="<?php echo $this->escape($row->title) ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>						        			
                                      </td> --> 
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('ul.tabs li:first-child').removeClass('active');
    });
</script>