<div id="diagTrBrandStore" style="display:none;">
    <form id="formTrBrandStore">
        <div class="section"><label>Locale</label><div><?php echo $this->tr_bs_form->locale ?></div></div>
        <div class="section"><label>Title</label><div><?php echo $this->tr_bs_form->title ?></div></div>
        <div class="section last"><label>Content</label><div><?php echo $this->tr_bs_form->content ?></div></div>
    </form>
</div>