<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>Brand Stores</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="#tab2">Translate Brand Stores</a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a brand store">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="languages" width="100%">
                                <thead>
                                    <tr>
                                        <th>Translate Brand Store ID</th>
                                        <th>Brand Store</th>
                                        <th>Locale</th>
                                        <th>Title</th>
                                        <th>Content</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->stores as $store): ?>
                                    <tr>
                                        <td><?php echo $store['tr_bsid'] ?></td>
                                        <td><?php echo $store['name'] ?></td>
                                        <td><?php echo $store['locale'] ?></td>
                                        <td><?php echo $store['title'] ?></td>
                                        <td><?php echo $store['content'] ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/translate-brand-stores/edit/id/<?php echo $store['tr_bsid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/translate-brand-stores/delete/id/<?php echo $store['tr_bsid'] ?>" class="delete" name="<?php echo $this->escape($store['title']); ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
