<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Politique QHSE</div>
                <div class="subtitle">POLITIQUE, QUALITE, HYGIENE, SECURITE ET ENVIRONNEMENT</div>
                <div class="text">
                    <p>Nous développons dès à présent des avantages compétitifs pour renforcer notre position de leader Européen dans le domaine du transport combiné de conteneurs maritimes.</p>
                    <p>Cette ambition conjuguée à une politique d’entreprise ambitieuse plaçe au premier rang de nos valeurs :</p>
                    <ul class="dash">
                        <li>La satisfaction des clients : Ponctualité des livraisons, information permanente sur le déroulement du transport et réactivité pour développer de nouvelles offres correspondant aux attentes du marché,</li>
                        <li>La réalisation des opérations de transport et de traction ferroviaire, dans le strict cadre des exigences réglementaires en matière de sécurité, de sûreté et d’environnement,</li>
                        <li>Le management du système environnemental par la réduction systémique des risques et des impacts environnementaux (prévention de toute pollution),</li>
                        <li>La profitabilité indispensable pour inscrire l’entreprise sur une trajectoire de développement durable,</li>
                        <li>Le développement personnel et professionnel des nos collaborateurs qui constituent un actif stratégique,</li>
                    </ul>
                    <p>Dans le cadre de cette ambition, nous nous engageons à développer le système de pilotage de la performance afin de renforcer nos valeurs :</p>
                    <div class="ul_title">La satisfaction et la fidélisation de nos clients</div>
                    <ul class="dash">
                        <li>Respect de notre neutralité qui garantit à tous les clients la même qualité de service et le même niveau d’engagement,</li>
                        <li>Ecoute permanente de nos clients pour bien prendre en compte leurs exigences dans le cadre des prestations proposées,</li>
                        <li>Respect par tous des règles de fonctionnement communes.</li>
                    </ul>
                    <div class="ul_title">L’amélioration continue de nos prestations et de nos processus internes</div>
                    <ul class="dash">
                        <li>Recherche permanente d’innovations commerciales, techniques et environnementales,</li>
                        <li>Diffusion des mesures relatives à la qualité des prestations fournies et à l’efficacité des processus,</li>
                        <li>Analyse régulière des différents indicateurs du Système Sécurité, Qualité & Environnement</li>
                    </ul>
                    <div class="ul_title">La maîtrise de notre production</div>
                    <ul class="dash">
                        <li>Respect strict des engagements pris et une amélioration continue des prestations fournies.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>