<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>Taxonomies</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="/admin/taxonomies">Taxonomies</a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="/admin/taxonomies/add" class="uibutton icon add" title="">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="world" width="100%">
                                <thead>
                                    <tr>
                                        <th>TAXO ID</th>
                                        <th>NAME</th>
                                        <th>PARENT</th>
                                        <th>POSITION</th>
                                        <th>SECTION</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->focusRowArray as $row): ?>
                                    <tr>
                                        <td><?php echo $row['tid'] ?></td>
                                        <td><?php echo $row['name'] ?></td>
                                        <td><?php echo $row['parent'] ?></td>
                                        <td><?php echo $row['pos'] ?></td>
                                        <td><?php echo strtoupper($row['section']) ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/taxonomies/edit/id/<?php echo $row['tid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/taxonomies/delete/id/<?php echo $row['tid'] ?>" class="delete" name="<?php echo $row['name'] ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>		
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
