<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('taxonomies') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li ><a href="#tab2"><?php echo $this->translate('taxonomies') ?></a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <!--
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title=""><?php echo $this->translate('') ?></a></li>
                        </ul>
                        -->
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="world" width="100%">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate('Taxo ID') ?></th>
                                        <th><?php echo $this->translate('Parent ID') ?></th>
                                        <th><?php echo $this->translate('Position') ?></th>
                                        <th><?php echo $this->translate('Section') ?></th>
                                        <th><?php echo $this->translate('Action') ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->focusRowArray as $row): ?>
                                    <tr>
                                        <td><?php echo $row['tid'] ?></td>
                                        <td><?php echo $row['parent_id'] ?></td>
                                        <td><?php echo $row['pos'] ?></td>
                                        <td><a href="<?php echo $this->url(array('action'=>'view', 'id'=>$row['tid'])) ?>"><?php echo $row['section'] ?></a></td>
                                        <td class="center">
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'edit', 'wid' => $row['tid']), 'default'); ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="<?php echo $this->url(array('action' => 'delete', 'wid' => $row['tid']), 'default'); ?>" class="delete" name="<?php echo $this->escape($row['section']) ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>		
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>
