<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span><?php echo $this->translate('taxonomies') ?></span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs">
                <li><a href="<?php echo $this->url(array('controller'=>'taxonomies', 'action' => 'index', 'module' => 'admin'), 'default', true) ?>"><?php echo $this->translate('taxonomies') ?></a></li> 
                <li class="active"><a href="#tab2"><?php //echo $this->id ?></a></li>
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <!--
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title=""><?php echo $this->translate('') ?></a></li>
                        </ul>
                        -->
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="world" width="100%">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate('Title') ?></th>
                                        <th><?php echo $this->translate('Locale') ?></th>
                                       <!-- <th><?php echo $this->translate('Action') ?></th> -->
                                    </tr>
                                </thead>
                                
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('ul.tabs li:first-child').removeClass('active');
    });
</script>