<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">ACTUALITÉS</div>
                <div class="text">
                    <ul class="news_list">
                        <?php if ($this->focusRowset) { ?>
                            <?php foreach ($this->focusRowset as $news) { ?>
                                <li>
                                    <div class="news_title"><?php echo $news->title ?></div>
                                    <div><?php echo substr($news->content, 0, 275) ?> <span class="read-more"> <a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'view','id'=>$news->post_id)) ?>">Lire la suite...</a></span></div>
                                </li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url("/medias/images/uploads/<?php echo $this->filename ?>") no-repeat 0 center');});
</script>