<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container">
                <div><a href="<?php echo $this->url(array('controller'=>'news', 'action'=>'index')) ?>">BACK</a></div>
                <div class="news_detail">
                    <div class="news_title"><?php echo $this->news->title; ?></div>
                    <div class="news_rdate"><?php echo date("d/m/y", strtotime($this->news->rdate))?></div>
                    <div class="news_content">
                        <p>
                            <?php echo $this->news->content ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('div#core .image_layer').css('background', 'transparent url("/medias/images/uploads/<?php echo $this->filename ?>") no-repeat 0 center');
        $('.navigation > li:nth-child(6)').addClass('active');
    });
</script>