<div class="widget" >
    <div class="header"><span ><span class="ico gray arrow_bidirectional"></span>Users</span></div>
    <div class="content">
        <div id="UITab">
            <ul class="tabs" >
                <li class="active"><a href="/admin/users">Users</a></li>            
            </ul>
            <div class="tab_container">
                <div id="tab2" class="tab_content"> 
                    <div class="load_page">
                        <ul class="uibutton-group">
                            <li><a href="<?php echo $this->url(array('action' => 'add')); ?>" class="uibutton icon add" title="Add a language">Add</a></li>
                        </ul>
                        <div class="tableName toolbar">
                            <h3><?php echo $this->translate('list') ?></h3>
                            <table class="display data_table2" id="users" width="100%">
                                <thead>
                                    <tr>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Company Name</th>
                                        <th>Email</th>
                                        <th>Power</th>
                                        <th>User Type</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->users as $user): ?>
                                    <tr>
                                        <td><?php echo $user['first_name'] ?></td>
                                        <td><?php echo $user['last_name'] ?></td>
                                        <td><?php echo $user['company_name'] ?></td>
                                        <td><?php echo $user['email'] ?></td>
                                        <td><?php echo $user['power'] ?></td>
                                        <td><?php echo $user['user_type'] ?></td>
                                        <td><?php echo $user['status'] ?></td>
                                        <td class="center">
                                            <span class="tip"><a href="/admin/users/edit/id/<?php echo $user['uid'] ?>" title="Editer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_edit.png" ></a></span> 
                                            <span class="tip"><a href="/admin/users/delete/id/<?php echo $user['uid'] ?>" class="delete" name="<?php echo $this->escape($user['email']) ?>" title="Supprimer"><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/icon_delete.png"></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>   
    </div>
</div>




<!--
<a href="<?php echo $this->url(array('action'=>'edit','id'=>$this->user->user_id))?>" >Edit Profile</a>

<table>
	<tr>
		<td>Username: </td>
		<td><?php echo $this->user->username;?></td>
	</tr>
	<tr>
		<td>Display name: </td>
		<td><?php echo $this->user->display_name;?></td>
	</tr>
	<tr>
		<td>Create Date: </td>
		<td><?php echo $this->user->cdate;?></td>
	</tr>
	<tr>
		<td>Last modified date: </td>
		<td><?php echo $this->user->mdate;?></td>
	</tr>
	<tr>
		<td>Last connected ip:</td>
		<td><?php echo $this->user->ip;?></td>
	</tr>
	<tr>
		<td>Status: </td>
		<td><?php echo $this->user->status;?></td>
	</tr>
	
</table>
-->
