<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>
        
       <title>Carburant admin version 1.0 online</title>

        <!-- Link shortcut icon-->
        <link rel="shortcut icon" type="image/ico" href="<?php echo $this->baseUrl(); ?>/medias/admin/images/favicon.ico"/> 

        <!-- Link css-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/css/zice.style.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/css/zice-custom.style.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/css/icon.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/css/ui-custom.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/css/timepicker.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/colorpicker/css/colorpicker.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/elfinder/css/elfinder.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/datatables/dataTables.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/validationEngine/validationEngine.jquery.css"/>     
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/jscrollpane/jscrollpane.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/fancybox/jquery.fancybox.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/tipsy/tipsy.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/editor/jquery.cleditor.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/chosen/chosen.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/confirm/jquery.confirm.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/sourcerer/sourcerer.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/fullcalendar/fullcalendar.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/Jcrop/jquery.Jcrop.css"/>  
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/uploadify/uploadify.css"/>  
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/admin/components/latitude-longitude-picker/css/jquery-gmaps-latlon-picker.css"/>  
		
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/flot/excanvas.min.js"></script><![endif]-->  
		
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/js/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/ui/jquery.ui.min.js"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/ui/jquery.autotab.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/ui/timepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/colorpicker/js/colorpicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/checkboxes/iphone.check.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/elfinder/js/elfinder.full.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/elfinder/js/i18n/elfinder.fr.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/datatables/dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/datatables/ColVis.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/scrolltop/scrolltopcontrol.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/fancybox/jquery.fancybox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/jscrollpane/mousewheel.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/jscrollpane/mwheelIntent.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/jscrollpane/jscrollpane.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/spinner/ui.spinner.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/tipsy/jquery.tipsy.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/editor/jquery.cleditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/chosen/chosen.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/confirm/jquery.confirm.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/validationEngine/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/validationEngine/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/vticker/jquery.vticker-min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/sourcerer/sourcerer.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/fullcalendar/fullcalendar.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/flot/flot.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/flot/flot.pie.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/flot/flot.resize.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/flot/graphtable.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/uploadify/uploadify.js"></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/checkboxes/customInput.jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/effect/jquery-jrumble.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/filestyle/jquery.filestyle.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/placeholder/jquery.placeholder.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/Jcrop/jquery.Jcrop.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/imgTransform/jquery.transform.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/webcam/webcam.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/rating_star/rating_star.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/dualListBox/dualListBox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/smartWizard/jquery.smartWizard.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/maskedinput/jquery.maskedinput.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/highlightText/highlightText.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/elastic/jquery.elastic.source.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/js/zice.custom.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/ckeditor/adapters/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/js/dialog-patch.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/admin/components/latitude-longitude-picker/js/jquery-gmaps-latlon-picker.js"></script>
        
   
           
	</head>        
        <body class="dashborad">        
        <div id="alertMessage" class="error"></div>
		<!-- Header -->
        <div id="header">
                <div id="account_info">
                    <div class="setting" title="Profile Setting"><b>Bienvenue,</b> <b class="red"><?php echo $this->displayname; ?></b><img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/gear.png" class="gear"  alt="Profile Setting" ></div>
                    <div class="logout" title="Disconnect"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'login','action' => 'logout'), 'default', true); ?>"><b >Logout</b> <img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/connect.png" name="connect" class="disconnect" alt="disconnect" ></a></div> 
                </div>
            </div><!-- End Header -->
			<div id="shadowhead"></div>
                   
              <div id="left_menu">
                    <ul id="main_menu" class="main_menu">
                      <li class="limenu<?php if($this->selectedDashboard): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'dashboard'), 'default', true); ?>"><span class="ico gray shadow home" ></span><b><?php echo $this->translate('Dashboard') ?></b></a></li>
                      <li class="limenu<?php if($this->selectedLanguages): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'languages'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b><?php echo $this->translate('Languages') ?></b></a></li>
                      <li class="limenu<?php if($this->selectedWorld): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'world'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>World</b></a>
                          <ul>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'world',), 'default', true); ?>">World</a></li>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'translate-world',), 'default', true); ?>">Translate World</a></li>
                          </ul>
                      </li>
                      
                      <li class="limenu<?php if($this->selectedUsers): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'users'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Users</b></a></li>
                      <li class="limenu<?php if($this->selectedTaxonomies): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'taxonomies'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Taxonomies</b></a>
                          <ul>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'taxonomies',), 'default', true); ?>">Taxonomies</a></li>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'translate-taxonomies',), 'default', true); ?>">Translate Taxonomies</a></li>
                          </ul>
                      </li>                      
                      <li class="limenu<?php if($this->selectedBrands): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'brands'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Brands</b></a></li>
                      <li class="limenu<?php if($this->selectedBrandStores): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'brand-stores'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Brand Stores</b></a>
                          <ul>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'brand-stores',), 'default', true); ?>">Brand Stores</a></li>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'translate-brand-stores',), 'default', true); ?>">Translate Brand Stores</a></li>
                          </ul>
                      </li>
                      <li class="limenu<?php if($this->selectedBrandCampaigns): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'brand-campaigns'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Brand Campaigns</b></a></li>
                      <li class="limenu<?php if($this->selectedArticles): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'articles'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Articles</b></a></li>
                      <li class="limenu<?php if($this->selectedHotels): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'hotels'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Hotels</b></a>
                          <ul>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'hotels',), 'default', true); ?>">Hotels</a></li>
                              <li><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'translate-hotels',), 'default', true); ?>">Translate Hotels</a></li>
                          </ul>
                      </li>
                      <li class="limenu<?php if($this->selectedHotelUsers): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'hotel-users'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Hotel Users</b></a></li>

                      <li class="limenu<?php if($this->selectedMessages): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'messages'), 'default', true); ?>"><span class="ico gray shadow window" ></span><b>Messages</b></a></li>
                    </ul>
               </div>
            
              <div id="content">
                <div class="inner">
					<div class="topcolumn">
						<div class="logo"></div>
                            <ul  id="shortcut">
                                <li> <a href="<?php echo $this->url(array('module' => 'admin' ,'controller' => 'dashboard'), 'default', true); ?>" title="Back To home"> <img src="<?php echo $this->baseUrl(); ?>/medias/admin/images/icon/shortcut/home.png" alt="home"/><strong>Home</strong> </a> </li>
                            </ul>
							<div class="clear"></div>
					</div>
                    <div class="clear"></div>
                    
					<!-- full width -->
 
 
					<?php echo $this->layout()->content; ?>
                        
					<!-- clear fix -->
					<div class="clear"></div>

                    <div id="footer"> 
                    	<div style="float:left;">&copy; Copyright 2012  All Rights Reserved <span class="tip"><a  href="http://www.carburant.fr/" target="_blank" title="Carburant Admin" >Carburant</a> </span></div> 
                    </div>

                </div> <!--// End inner -->
              </div> <!--// End content --> 
</body>
</html>