<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="fr"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="fr"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="fr"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="fr"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Naviland Cargo</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/fonts.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/menu.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/medias/js/libs/jquery-1.5.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/medias/admin/components/ui/jquery.ui.min.js"></script>
</head>
<body id="<?php echo $this->action ?>">
    <!--[if lt IE 7]><p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p><![endif]-->
    <div class="page">
        
        <!-- start header -->
        <div id="header">
            <div id="logo">
                <div class="inner"><a href="/"><img src='/medias/images/logo.png'></a></div>
            </div>
            <div id="header_right">
                <div id="logo_afaq"><div class="inner"><img src="/medias/images/logo_afaq.png"></div></div>
                <div id="menu">
                    <?php if (isset($_COOKIE['locale']) && $_COOKIE['locale'] == 'en_US') { ?>
                        <div><?php echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('navigation_en')); ?></div>
                        <div id="breadcrumbs"><div class="inner"><a href="/">Home Page</a> > <?php echo $this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->render(Zend_Registry::get('navigation_en')); ?></div></div>
                    <?php } else { ?>
                        <?php echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('navigation_fr')); ?>
                        <div id="breadcrumbs"><div class="inner"><a href="/">Home Page</a> > <?php echo $this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->render(Zend_Registry::get('navigation_fr')); ?></div></div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- end header -->
        
        <!-- start main -->
        <div id="main">
            <div id="core">
                <?php echo $this->layout()->content; ?>
            </div>
            <div>
                <?php if ($this->layout()->widge) : ?>
                <div id="widge">
                    <div class="inner">
                        <ul><?php echo $this->layout()->widge; ?></ul>
                    </div>
                </div>
                <?php endif; ?>
                
            </div>
        </div>
        <!-- end main -->
        
        <div id="footer">
            <div class="inner">
                <a>Crédits</a>
                |
                <a>Plan du Site</a>
                |
                <a>Mentions légales</a>
                <img src="/medias/images/LOGO_FACEBOOK.png"> <img src="/medias/images/LOGO_TWITTER.png"> 
                    Langues 
                    <a href="" onclick="setCookie('locale', 'en_US')"><img src="/medias/images/LOGO_ENGLISH.png"></a>
                    <a href="" onclick="setCookie('locale', 'fr_FR')"><img src="/medias/images/LOGO_FRANCH.png"></a>
            </div>
        </div>
        <div id="fb-root"></div>
    </div>
    <script src="<?php echo $this->baseUrl(); ?>/medias/js/script.js"></script>
    <!--[if IE]><script src="<?php echo $this->baseUrl(); ?>/medias/js/ie_script.js"></script><![endif]-->
</body>
</html>