<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="fr"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="fr"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="fr"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="fr"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Naviland Cargo</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/fonts.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/menu.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/medias/js/libs/jquery-1.5.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/medias/admin/components/ui/jquery.ui.min.js"></script>
</head>
<body id="<?php echo $this->action ?>">
    <!--[if lt IE 7]><p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p><![endif]-->
    <div class="page">
        
        <!-- start header -->
        <!-- end header -->
        
        <!-- start main -->
        <div id="main">
            <div id="core">
                <?php echo $this->layout()->content; ?>
            </div>
            <div>
                <?php if ($this->layout()->widge) : ?>
                <div id="widge">
                    <div class="inner">
                        <ul><?php echo $this->layout()->widge; ?></ul>
                    </div>
                </div>
                <?php endif; ?>
                
            </div>
        </div>
        <!-- end main -->
        
        <div id="footer">
            <div class="inner">
            </div>
        </div>
        <div id="fb-root"></div>
    </div>
    <script src="<?php echo $this->baseUrl(); ?>/medias/js/script.js"></script>
    <!--[if IE]><script src="<?php echo $this->baseUrl(); ?>/medias/js/ie_script.js"></script><![endif]-->
</body>
</html>
