<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="fr"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="fr"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="fr"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="fr"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Naviland Cargo</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/fonts.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/menu.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/medias/js/libs/jquery-1.5.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/medias/admin/components/ui/jquery.ui.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/medias/js/libs/modernizr-2.6.1.min.js"></script>
</head>
<body class="home">
    <!--[if lt IE 7]><p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p><![endif]-->
    <div class="page">
        <!-- start header -->
        <div id="header" class="whitesmoke">
            <div id="logo">
                <div class="inner"><a href="/"><img src='/medias/images/logo.png'></a></div>
            </div>
            <div id="header_right">
                <div id="logo_afaq"><div class="inner"><img src="/medias/images/logo_afaq.png"></div></div>
                <div id="menu">
                    <div>
                        <?php 
                        if (isset($_COOKIE['locale']) && $_COOKIE['locale'] == 'en_US') {
                            echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('navigation_en'));
                        } else
                            echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('navigation_fr'));
                        ?>
                     </div>       
                </div>
            </div>
        </div>
        <!-- end header -->
        
        <div id="main">
        </div>
        
        <div id="footer">
            <div class="inner whitesmoke">
                <a>Crédits</a>
                |
                <a>Plan du Site</a>
                |
                <a>Mentions légales</a>
                <img src="/medias/images/LOGO_FACEBOOK.png"> <img src="/medias/images/LOGO_TWITTER.png"> 
                    Langues 
                    <a href="" onclick="setCookie('locale', 'en_US')"><img src="/medias/images/LOGO_ENGLISH.png"></a>
                    <a href="" onclick="setCookie('locale', 'fr_FR')"><img src="/medias/images/LOGO_FRANCH.png"></a>
            </div>
        </div>
    </div>
    <script src="<?php echo $this->baseUrl(); ?>/medias/js/script.js"></script>
    <!--[if IE]><script src="<?php echo $this->baseUrl(); ?>/medias/js/ie_script.js"></script><![endif]-->
    <script type="text/javascript">
        $(document).ready(function(){});
    </script>
</body>
</html>